Automaton Core: automaton::core::network::http_session Class Reference
automaton::core::network::http_session Class Reference
#include <http_server.h>
Public Member Functions
http_session (boost::asio::io_service &io_service, std::shared_ptr< http_server::server_handler >)
std::string add_http_header (const std::string &body, http_server::status_code s) const
void read_body (uint32_t body_size)
void read_header ()
boost::asio::ip::tcp::socket & socket ()
void start ()
Constructor & Destructor Documentation
http_session()
automaton::core::network::http_session::http_session (boost::asio::io_service & io_service, std::shared_ptr< http_server::server_handler > sh)
Member Function Documentation
add_http_header()
std::string automaton::core::network::http_session::add_http_header (const std::string & body, http_server::status_code s) const
Referenced by read_body().
read_body()
void automaton::core::network::http_session::read_body (uint32_t body_size)
References add_http_header(), and automaton::core::interop::ethereum::string.
Referenced by read_header().
read_header()
void automaton::core::network::http_session::read_header ()
References CRLF, read_body(), and automaton::core::interop::ethereum::string.
Referenced by start().
socket()
tcp::socket & automaton::core::network::http_session::socket ()
Referenced by automaton::core::network::http_server::http_server(), and automaton::core::network::http_server::handle_accept().
start()
void automaton::core::network::http_session::start ()
References read_header().
Referenced by automaton::core::network::http_server::handle_accept().
The documentation for this class was generated from the following files:
http_server.h
http_server.cc