Automaton Core: automaton::core::crypto::cryptopp::secp256k1_cryptopp Class Reference
automaton::core::crypto::cryptopp::secp256k1_cryptopp Class Reference
#include <secp256k1_cryptopp.h>
Public Member Functions
void gen_public_key (const uint8_t *private_key, uint8_t *public_key)
bool has_deterministic_signatures ()
size_t k_size ()
size_t private_key_size ()
size_t public_key_size ()
void sign (const uint8_t *private_key, const uint8_t *message, const size_t msg_len, uint8_t *signature)
void sign_deterministic (const uint8_t *private_key, const uint8_t *message, const size_t msg_len, const uint8_t *k, uint8_t *signature)
size_t signature_size ()
bool verify (const uint8_t *public_key, const uint8_t *message, const size_t msg_len, const uint8_t *signature)
Public Member Functions inherited from automaton::core::crypto::digital_signature
virtual ~digital_signature ()
Member Function Documentation
gen_public_key()
void automaton::core::crypto::cryptopp::secp256k1_cryptopp::gen_public_key (const uint8_t * private_key, uint8_t * public_key) virtual
Generates a public key from the given private key.
The format is implementation specific.
Parameters
[in] private_key the private key as a buffer.
[out] public_key a pointer to the buffer to recive the public key.
Precondition
public_key_size() == public_key in bytes.
private_key_size() == private_key in bytes.
Implements automaton::core::crypto::digital_signature.
References private_key_size().
has_deterministic_signatures()
bool automaton::core::crypto::cryptopp::secp256k1_cryptopp::has_deterministic_signatures () virtual
Returns true of this implementation can sign deterministic signatures using the sign_deterministic() function
Implements automaton::core::crypto::digital_signature.
k_size()
size_t automaton::core::crypto::cryptopp::secp256k1_cryptopp::k_size () virtual
The size of the random k in bytes;
Implements automaton::core::crypto::digital_signature.
private_key_size()
size_t automaton::core::crypto::cryptopp::secp256k1_cryptopp::private_key_size () virtual
The size of the private key in bytes
Implements automaton::core::crypto::digital_signature.
Referenced by gen_public_key(), and sign().
public_key_size()
size_t automaton::core::crypto::cryptopp::secp256k1_cryptopp::public_key_size () virtual
The size of the public key in bytes
Implements automaton::core::crypto::digital_signature.
Referenced by verify().
sign()
void automaton::core::crypto::cryptopp::secp256k1_cryptopp::sign (const uint8_t * private_key, const uint8_t * message, const size_t msg_len, uint8_t * signature) virtual
Signs a message using a private key and a message.
Parameters
[in] private_key the private key as a buffer.
[in] message the message as a pointer to a buffer.
[in] msg_len the lenght of the message that will be signed.
[out] signature a pointer to the buffer to receive the signature.
Precondition
Precondition signature_size() == signature in bytes.
Implements automaton::core::crypto::digital_signature.
References private_key_size(), signature_size(), and automaton::core::interop::ethereum::string.
sign_deterministic()
void automaton::core::crypto::cryptopp::secp256k1_cryptopp::sign_deterministic (const uint8_t * private_key, const uint8_t * message, const size_t msg_len, const uint8_t * k, uint8_t * signature) virtual
Signs a deterministic message using a private key, random k and message.
Parameters
[in] private_key the private key as a buffer
[in] message the message as a pointer to a buffer
[in] msg_len the lenght of the message that will be signed
[in] k the random k used the sign the message
[out] signature a pointer to the buffer to recive the signature
Precondition
Precondition signature_size() == signature in bytes.
Implements automaton::core::crypto::digital_signature.
signature_size()
size_t automaton::core::crypto::cryptopp::secp256k1_cryptopp::signature_size () virtual
The size of the signature in bytes
Implements automaton::core::crypto::digital_signature.
Referenced by sign(), and verify().
verify()
bool automaton::core::crypto::cryptopp::secp256k1_cryptopp::verify (const uint8_t * public_key, const uint8_t * message, const size_t msg_len, const uint8_t * signature) virtual
Verifies that a message was signed by the privated key coresponding to the given public key.
Parameters
[in] public_key the public key as a buffer
[in] message the message as a pointer to a buffer
[in] msg_len the lenght of the message
[in] signature a pointer to the buffer to recive the signature
Implements automaton::core::crypto::digital_signature.
References public_key_size(), signature_size(), and automaton::core::interop::ethereum::string.
The documentation for this class was generated from the following files:
secp256k1_cryptopp.h
secp256k1_cryptopp.cc