Automaton Core: automaton::core::interop::ethereum::eth_contract Class Reference
automaton::core::interop::ethereum::eth_contract Class Reference
#include <eth_contract_curl.h>
Public Member Functions
eth_contract (const std::string &server, const std::string &address, const std::string &abi_json)
~eth_contract ()
common::status call (const std::string &fname, const std::string &params, const std::string &private_key="", const std::string &value="", const std::string &gas_price="", const std::string &gas_limit="")
std::string get_gas_limit ()
std::string get_gas_price ()
void set_gas_limit (const std::string &new_gas_limit_hex)
void set_gas_price (const std::string &new_gas_price_hex)
Static Public Member Functions
static std::shared_ptr< eth_contract > get_contract (const std::string &)
static void register_contract (const std::string &server, const std::string &address, const std::string &abi_json)
Static Public Attributes
static std::unordered_map< std::string, std::shared_ptr< eth_contract > > contracts
Detailed Description
Class storing Ethereum contract address and function signatures. It is used to send eth_call requests to the Ethereum network and pass the result to a given callback function. This class is NOT thread safe. If functions are called simultaneously, it won't work correctly.
Constructor & Destructor Documentation
eth_contract()
automaton::core::interop::ethereum::eth_contract::eth_contract (const std::string & server, const std::string & address, const std::string & abi_json)
References automaton::core::common::status::code, automaton::core::interop::ethereum::eth_gasPrice(), and automaton::core::common::status::msg.
Referenced by register_contract().
~eth_contract()
automaton::core::interop::ethereum::eth_contract::~eth_contract ()
Member Function Documentation
call()
status automaton::core::interop::ethereum::eth_contract::call (const std::string & fname, const std::string & params, const std::string & private_key = "", const std::string & value = "", const std::string & gas_price = "", const std::string & gas_limit = "")
Parameters
[in] fname function name/alias as given in register_contract
[in] params case 1: sending raw transaction -> params is signed transaction case 2: params is list in json format where 'bytes' and 'address' are given in hex, integers in decimal, 'string' is string, 'boolean' is "true" or "false" (without quotes) ! 'fixed' numbers are not yet supported !
[in] private_key in hex (without 0x prefix)
[in] gas_price in hex (without 0x prefix)
[in] gas_limit in hex (without 0x prefix)
[in] value in hex (without 0x prefix)
Returns
status code: 1) if function call was successful status code is 'OK' and status msg contains the function result: transaction receipt if the function is a transaction, decoded function result in json format, otherwise 2) if function call failed status code shows error type and status msg contains the error
References automaton::core::io::bin2hex(), automaton::core::common::status::code, automaton::core::interop::ethereum::curl_post(), automaton::core::interop::ethereum::encode(), automaton::core::interop::ethereum::eth_getTransactionReceipt(), automaton::core::interop::ethereum::get_address_from_prkey(), automaton::core::common::status::msg, and automaton::core::interop::ethereum::string.
get_contract()
std::shared_ptr< eth_contract > automaton::core::interop::ethereum::eth_contract::get_contract (const std::string & address) static
References contracts.
Referenced by main().
get_gas_limit()
std::string automaton::core::interop::ethereum::eth_contract::get_gas_limit ()
get_gas_price()
std::string automaton::core::interop::ethereum::eth_contract::get_gas_price ()
register_contract()
void automaton::core::interop::ethereum::eth_contract::register_contract (const std::string & server, const std::string & address, const std::string & abi_json) static
Parameters
[in] server ip address or url
[in] address contract address on ethereum main or testnet
[in] abi_json contract abi as json string
References eth_contract(), and contracts.
Referenced by main().
set_gas_limit()
void automaton::core::interop::ethereum::eth_contract::set_gas_limit (const std::string & new_gas_limit_hex)
set_gas_price()
void automaton::core::interop::ethereum::eth_contract::set_gas_price (const std::string & new_gas_price_hex)
Member Data Documentation
contracts
std::unordered_map< std::string, std::shared_ptr< eth_contract > > automaton::core::interop::ethereum::eth_contract::contracts static
Referenced by get_contract(), and register_contract().
The documentation for this class was generated from the following files:
eth_contract_curl.h
eth_contract_curl.cc