Automaton Core: automaton::tools::miner Namespace Reference
automaton::tools::miner Namespace Reference
Functions
std::string gen_pub_key (const unsigned char *priv_key)
unsigned int mine_key (unsigned char *mask, unsigned char *difficulty, unsigned char *priv_key, int max_attempts)
std::string sign (const unsigned char *priv_key, const unsigned char *msg_hash)
std::string str_tohex (std::string s)
Function Documentation
gen_pub_key()
std::string automaton::tools::miner::gen_pub_key (const unsigned char * priv_key)
References automaton::core::io::bin2hex(), and automaton::core::interop::ethereum::string.
Referenced by main().
mine_key()
unsigned int automaton::tools::miner::mine_key (unsigned char * mask, unsigned char * difficulty, unsigned char * priv_key, int max_attempts)
References automaton::core::io::bin2hex(), and automaton::core::interop::ethereum::string.
Referenced by main().
sign()
std::string automaton::tools::miner::sign (const unsigned char * priv_key, const unsigned char * msg_hash)
References automaton::core::interop::ethereum::string.
Referenced by check_and_sign(), automaton::core::interop::ethereum::dec_to_i256(), automaton::core::interop::ethereum::i256_to_dec(), and main().
str_tohex()
std::string automaton::tools::miner::str_tohex (std::string s)