Automaton Core: automaton::core::data::factory Class Reference
automaton::core::data::factory Class Reference abstract
#include <factory.h>
Public Member Functions
virtual ~factory ()=0
virtual std::string dump_enum (uint32_t enum_id) const =0
virtual std::string dump_message_schema (uint32_t schema_id) const =0
virtual std::string get_enum_field_type (uint32_t schema_id, uint32_t tag) const =0
virtual uint32_t get_enum_id (const std::string &enum_name) const =0
virtual int32_t get_enum_value (uint32_t enum_id, const std::string &value_name) const =0
virtual std::vector< std::pair< std::string, int32_t > > get_enum_values (uint32_t enum_id) const =0
virtual uint32_t get_enums_number () const =0
virtual schema::field_info get_field_info (uint32_t schema_id, uint32_t index) const =0
virtual uint32_t get_field_tag (uint32_t schema_id, const std::string &name) const =0
virtual std::string get_field_type (uint32_t schema_id, uint32_t tag) const =0
virtual uint32_t get_fields_number (uint32_t schema_id) const =0
virtual std::string get_message_field_type (uint32_t schema_id, uint32_t tag) const =0
virtual uint32_t get_nested_message_schema_id (uint32_t schema_id, uint32_t index) const =0
virtual uint32_t get_nested_messages_number (uint32_t schema_id) const =0
virtual uint32_t get_schema_id (const std::string &schema_name) const =0
virtual std::string get_schema_name (uint32_t schema_id) const =0
virtual uint32_t get_schemas_number () const =0
virtual void import_schema (schema *schema, const std::string &name, const std::string &package)=0
virtual bool is_repeated (uint32_t schema_id, uint32_t tag) const =0
virtual std::unique_ptr< msg > new_message_by_id (uint32_t message_type_id)=0
virtual std::unique_ptr< msg > new_message_by_name (const char *schema_name)=0
Detailed Description
Schema data structure interface.
Constructor & Destructor Documentation
~factory()
automaton::core::data::factory::~factory () pure virtual
Member Function Documentation
dump_enum()
virtual std::string automaton::core::data::factory::dump_enum (uint32_t enum_id) const pure virtual
Prints information about an enum and its values. If the given enum id is not valid, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
dump_message_schema()
virtual std::string automaton::core::data::factory::dump_message_schema (uint32_t schema_id) const pure virtual
Prints information about a message schema and its fields. If the given schema id is not valid, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
get_enum_field_type()
virtual std::string automaton::core::data::factory::get_enum_field_type (uint32_t schema_id, uint32_t tag) const pure virtual
If the type of the field is enum, returns the fully-qualified name of the enum type. If the given schema id is not valid or if there is no field with the given tag or the field type is not enum, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
get_enum_id()
virtual uint32_t automaton::core::data::factory::get_enum_id (const std::string & enum_name) const pure virtual
Get the id of the enum with enum_name. Id is needed for getting information about the enum values. If enum with the given name doesn't exist, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
get_enum_value()
virtual int32_t automaton::core::data::factory::get_enum_value (uint32_t enum_id, const std::string & value_name) const pure virtual
Returns enum value matching value name. If no such enum or name exists, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
get_enum_values()
virtual std::vector<std::pair<std::string, int32_t> > automaton::core::data::factory::get_enum_values (uint32_t enum_id) const pure virtual
Returns a vector of pairs containing info about the values in this enum. A pair represents the string name of the value and the int value. If no such enum exists, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
get_enums_number()
virtual uint32_t automaton::core::data::factory::get_enums_number () const pure virtual
Returns the number of enums in the whole schema definition (both top-level and nested).
Implemented in automaton::core::data::protobuf::protobuf_factory.
get_field_info()
virtual schema::field_info automaton::core::data::factory::get_field_info (uint32_t schema_id, uint32_t index) const pure virtual
Returns info about the specified field. Index must be >= 0 and < get_fields_number(schema_id). If no such schema or such field exists, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
get_field_tag()
virtual uint32_t automaton::core::data::factory::get_field_tag (uint32_t schema_id, const std::string & name) const pure virtual
Returns the tag of the field with the given name in the schema with the given id. If the given schema id is not valid or there is no field with the given name, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
get_field_type()
virtual std::string automaton::core::data::factory::get_field_type (uint32_t schema_id, uint32_t tag) const pure virtual
Returns the type (as a string) of the field with the given tag in the schema with the given id. If the given schema id is not valid or there is no field with the given tag, exception will be thrown.
If the type is message, returns 'message'. To get the type of a message field use get_message_field_type().
If the type is enum, returns 'enum'. To get the type of a enum field use get_enum_field_type().
Use the result of this function in set_*() and get_*() and in set_repeated_*() and get_repeated_*() if the field is repeated.
Implemented in automaton::core::data::protobuf::protobuf_factory.
get_fields_number()
virtual uint32_t automaton::core::data::factory::get_fields_number (uint32_t schema_id) const pure virtual
Returns the number of fields in the schema with the given id. If no such schema exists, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
get_message_field_type()
virtual std::string automaton::core::data::factory::get_message_field_type (uint32_t schema_id, uint32_t tag) const pure virtual
If the type of the field is message, returns the fully-qualified name of the message type. If the given schema id is not valid or if there is no field with the given tag or the field type is not message, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
get_nested_message_schema_id()
virtual uint32_t automaton::core::data::factory::get_nested_message_schema_id (uint32_t schema_id, uint32_t index) const pure virtual
Returns the schema id of the corresponding nested message.
Implemented in automaton::core::data::protobuf::protobuf_factory.
Referenced by automaton::core::script::module::bind_schemas().
get_nested_messages_number()
virtual uint32_t automaton::core::data::factory::get_nested_messages_number (uint32_t schema_id) const pure virtual
Returns the number of nested message types in the specified message schema.
Implemented in automaton::core::data::protobuf::protobuf_factory.
Referenced by automaton::core::script::module::bind_schemas().
get_schema_id()
virtual uint32_t automaton::core::data::factory::get_schema_id (const std::string & schema_name) const pure virtual
Returns the id of the schema with schema_name. Id is needed for creating new messages of that type, also getting information about the fields. If schema with the given name doesn't exist, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
Referenced by automaton::core::script::module::bind_schemas(), automaton::core::script::module::check_implementation(), automaton::core::data::protobuf::protobuf_msg::get_message(), and automaton::core::data::protobuf::protobuf_msg::get_repeated_message().
get_schema_name()
virtual std::string automaton::core::data::factory::get_schema_name (uint32_t schema_id) const pure virtual
Returns the name of the schema of message with the given id. If schema with the given name doesn't exist, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
Referenced by automaton::core::script::module::bind_schemas().
get_schemas_number()
virtual uint32_t automaton::core::data::factory::get_schemas_number () const pure virtual
Returns the number of messages in the whole schema definition (both top-level and nested).
Implemented in automaton::core::data::protobuf::protobuf_factory.
import_schema()
virtual void automaton::core::data::factory::import_schema (schema * schema, const std::string & name, const std::string & package) pure virtual
This function is used for include schema definitions that were created with schema. If the given schema has dependencies, they must be imported first or exception will be thrown. Name will be used for reference in schema::add_dependency(). Package is used in fully_qualified_type.
Implemented in automaton::core::data::protobuf::protobuf_factory.
is_repeated()
virtual bool automaton::core::data::factory::is_repeated (uint32_t schema_id, uint32_t tag) const pure virtual
Returns true if the field is repeated, false, otherwise. If the given schema id is not valid or if there is no field with the given tag, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
new_message_by_id()
virtual std::unique_ptr<msg> automaton::core::data::factory::new_message_by_id (uint32_t message_type_id) pure virtual
Creates new message from a schema with message_type_id. Returns the created message that is used for setting and getting data, serializing and deserializing, etc.
If the given message_type_id is not valid, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
new_message_by_name()
virtual std::unique_ptr<msg> automaton::core::data::factory::new_message_by_name (const char * schema_name) pure virtual
Creates new message from a schema name.
Returns the created message that is used for setting and getting data, serializing and deserializing, etc.
If the given schema_name is not valid, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_factory.
The documentation for this class was generated from the following files:
factory.h
factory.cc