Automaton Core: automaton::core::testnet::testnet Class Reference
automaton::core::testnet::testnet Class Reference
#include <testnet.h>
Public Types
enum network_protocol_type { localhost = 1, simulation = 2 }
Public Member Functions
~testnet ()
void connect (const std::unordered_map< uint32_t, std::vector< uint32_t > > &peers_list) const
std::vector< std::string > list_nodes ()
Static Public Member Functions
static bool create_testnet (const std::string &node_type, const std::string &id, const std::string &smart_protocol_id, network_protocol_type ntype, uint32_t number_nodes, std::unordered_map< uint32_t, std::vector< uint32_t > > peer_list)
static void destroy_testnet (const std::string &id)
static std::shared_ptr< testnet > get_testnet (const std::string &id)
static std::vector< std::string > list_testnets ()
Member Enumeration Documentation
network_protocol_type
enum automaton::core::testnet::testnet::network_protocol_type
Enumerator
localhost
simulation
Constructor & Destructor Documentation
~testnet()
automaton::core::testnet::testnet::~testnet ()
References automaton::core::node::node::remove_node().
Member Function Documentation
connect()
void automaton::core::testnet::testnet::connect (const std::unordered_map< uint32_t, std::vector< uint32_t > > & peers_list) const
References automaton::core::node::node::add_peer(), automaton::core::node::node::connect(), automaton::core::node::node::get_node(), automaton::core::testnet::STARTING_PORT, and automaton::core::interop::ethereum::string.
create_testnet()
bool automaton::core::testnet::testnet::create_testnet (const std::string & node_type, const std::string & id, const std::string & smart_protocol_id, network_protocol_type ntype, uint32_t number_nodes, std::unordered_map< uint32_t, std::vector< uint32_t > > peer_list) static
destroy_testnet()
void automaton::core::testnet::testnet::destroy_testnet (const std::string & id) static
get_testnet()
std::shared_ptr< testnet > automaton::core::testnet::testnet::get_testnet (const std::string & id) static
list_nodes()
std::vector< std::string > automaton::core::testnet::testnet::list_nodes ()
Referenced by main().
list_testnets()
std::vector< std::string > automaton::core::testnet::testnet::list_testnets () static
The documentation for this class was generated from the following files:
testnet.h
testnet.cc