Automaton Core: eth_contract_curl_test.cc File Reference
eth_contract_curl_test.cc File Reference
#include <algorithm>
#include <fstream>
#include <iostream>
#include <memory>
#include <string>
#include <utility>
#include <curl/curl.h>
#include <json.hpp>
#include "automaton/core/interop/ethereum/eth_contract_curl.h"
#include "automaton/core/interop/ethereum/eth_helper_functions.h"
#include "automaton/core/interop/ethereum/eth_transaction.h"
#include "automaton/core/io/io.h"
#include "automaton/tools/miner/miner.h"
Typedefs
using json = nlohmann::json
Functions
void callback_func (const automaton::core::common::status &s, const std::string &response)
int main ()
Variables
static const char * ADDRESS = "0x603CB0d1c8ab86E72beb3c7DF564A36D7B85ecD2"
static const char * CONTRACT_ADDR = "0x4B7c78aB094Ab856eAdA523Fa847236567e1750E"
static const char * JSON_FILE = "../contracts/koh/build/contracts/KingAutomaton.json"
static const char * PRIVATE_KEY = "56aac550d97013a8402c98e3b2aeb20482d19f142a67022d2ab357eb8bb673b0"
static const char * URL = "127.0.0.1:7545"
Typedef Documentation
json
using json = nlohmann::json
Function Documentation
callback_func()
void callback_func (const automaton::core::common::status & s, const std::string & response)
main()
int main ()
References ADDRESS, automaton::core::io::bin2hex(), automaton::core::interop::ethereum::eth_transaction::chain_id, automaton::core::common::status::code, CONTRACT_ADDR, automaton::core::interop::ethereum::eth_transaction::data, automaton::core::io::dec2hex(), automaton::core::interop::ethereum::dec_to_i256(), automaton::core::interop::ethereum::eth_gasPrice(), automaton::core::interop::ethereum::eth_getCode(), automaton::core::interop::ethereum::eth_getTransactionCount(), automaton::core::interop::ethereum::eth_transaction::gas_limit, automaton::core::interop::ethereum::eth_transaction::gas_price, automaton::tools::miner::gen_pub_key(), automaton::core::interop::ethereum::eth_contract::get_contract(), automaton::core::io::hex2bin(), automaton::core::io::hex2dec(), JSON_FILE, automaton::tools::miner::mine_key(), automaton::core::common::status::msg, automaton::core::interop::ethereum::eth_transaction::nonce, automaton::core::common::status::OK, PRIVATE_KEY, automaton::core::interop::ethereum::eth_contract::register_contract(), automaton::tools::miner::sign(), automaton::core::interop::ethereum::eth_transaction::sign_tx(), automaton::core::interop::ethereum::string, automaton::core::interop::ethereum::eth_transaction::to, URL, and automaton::core::interop::ethereum::eth_transaction::value.
Variable Documentation
ADDRESS
const char* ADDRESS = "0x603CB0d1c8ab86E72beb3c7DF564A36D7B85ecD2" static
Referenced by main().
CONTRACT_ADDR
const char* CONTRACT_ADDR = "0x4B7c78aB094Ab856eAdA523Fa847236567e1750E" static
Referenced by main().
JSON_FILE
const char* JSON_FILE = "../contracts/koh/build/contracts/KingAutomaton.json" static
Referenced by main().
PRIVATE_KEY
const char* PRIVATE_KEY = "56aac550d97013a8402c98e3b2aeb20482d19f142a67022d2ab357eb8bb673b0" static
Referenced by main().
URL
const char* URL = "127.0.0.1:7545" static
Referenced by main().