Automaton Core: automaton::core::network::simulated_acceptor Class Reference
automaton::core::network::simulated_acceptor Class Reference
#include <simulated_connection.h>
Public Member Functions
simulated_acceptor (acceptor_id id, const std::string &address_, std::shared_ptr< acceptor::acceptor_handler > handler_, std::shared_ptr< connection::connection_handler > accepted_connections_handler)
~simulated_acceptor ()
std::string get_address () const
std::shared_ptr< acceptor_handler > get_handler ()
state get_state () const
bool init ()
bool parse_address (const std::string &address_, acceptor_params *params, uint32_t *parsed_address)
void set_state (acceptor::state new_state)
void start_accepting ()
void stop_accepting ()
Public Member Functions inherited from automaton::core::network::acceptor
virtual ~acceptor ()
acceptor_id get_id ()
Public Attributes
std::shared_ptr< connection::connection_handler > accepted_connections_handler
uint32_t address
std::string original_address
acceptor_params parameters
Additional Inherited Members
Public Types inherited from automaton::core::network::acceptor
typedef std::shared_ptr< acceptor >(* factory_function) (acceptor_id id, const std::string &address, std::shared_ptr< acceptor_handler > handler_, std::shared_ptr< connection::connection_handler > connections_handler)
enum state { invalid_state = 0, accepting = 1, not_accepting = 2 }
Static Public Member Functions inherited from automaton::core::network::acceptor
static std::shared_ptr< acceptor > create (const std::string &type, acceptor_id id, const std::string &address, std::shared_ptr< acceptor_handler > handler_, std::shared_ptr< connection::connection_handler > connections_handler)
static void register_acceptor_type (const std::string &type, factory_function func)
Protected Member Functions inherited from automaton::core::network::acceptor
acceptor (acceptor_id id, std::shared_ptr< acceptor_handler > handler_)
Protected Attributes inherited from automaton::core::network::acceptor
std::shared_ptr< acceptor_handler > handler
acceptor_id id
Constructor & Destructor Documentation
simulated_acceptor()
automaton::core::network::simulated_acceptor::simulated_acceptor (acceptor_id id, const std::string & address_, std::shared_ptr< acceptor::acceptor_handler > handler_, std::shared_ptr< connection::connection_handler > accepted_connections_handler)
~simulated_acceptor()
automaton::core::network::simulated_acceptor::~simulated_acceptor ()
Member Function Documentation
get_address()
std::string automaton::core::network::simulated_acceptor::get_address () const virtual
Returns
the acceptor's address
Implements automaton::core::network::acceptor.
References original_address.
get_handler()
std::shared_ptr< acceptor::acceptor_handler > automaton::core::network::simulated_acceptor::get_handler ()
References automaton::core::network::acceptor::handler.
get_state()
acceptor::state automaton::core::network::simulated_acceptor::get_state () const virtual
Returns
the acceptor's state
Implements automaton::core::network::acceptor.
init()
bool automaton::core::network::simulated_acceptor::init () virtual
Initialises the acceptor.
Returns
true if no errors occured and initialisation was successful, false, otherwise
Implements automaton::core::network::acceptor.
References address, automaton::core::network::simulation::get_simulator(), original_address, parameters, parse_address(), and set_state().
parse_address()
bool automaton::core::network::simulated_acceptor::parse_address (const std::string & address_, acceptor_params * params, uint32_t * parsed_address)
References automaton::core::network::acceptor_params::bandwidth, and automaton::core::network::acceptor_params::max_connections.
Referenced by init().
set_state()
void automaton::core::network::simulated_acceptor::set_state (acceptor::state new_state)
Referenced by init(), start_accepting(), and stop_accepting().
start_accepting()
void automaton::core::network::simulated_acceptor::start_accepting () virtual
The acceptor starts to listen for incoming connections.
Implements automaton::core::network::acceptor.
References address, and set_state().
stop_accepting()
void automaton::core::network::simulated_acceptor::stop_accepting () virtual
The acceptor stops to listen for incoming connections.
Implements automaton::core::network::acceptor.
References set_state().
Member Data Documentation
accepted_connections_handler
std::shared_ptr<connection::connection_handler> automaton::core::network::simulated_acceptor::accepted_connections_handler
address
uint32_t automaton::core::network::simulated_acceptor::address
Referenced by init(), and start_accepting().
original_address
std::string automaton::core::network::simulated_acceptor::original_address
Referenced by get_address(), and init().
parameters
acceptor_params automaton::core::network::simulated_acceptor::parameters
Referenced by init().
The documentation for this class was generated from the following files:
simulated_connection.h
simulated_connection.cc