Automaton Core: automaton::core::common::status Struct Reference
automaton::core::common::status Struct Reference
#include <status.h>
Public Types
enum status_code {
OK = 0, CANCELLED = 1, UNKNOWN = 2, INVALID_ARGUMENT = 3,
DEADLINE_EXCEEDED = 4, NOT_FOUND = 5, ALREADY_EXISTS = 6, PERMISSION_DENIED = 7,
UNAUTHENTICATED = 16, RESOURCE_EXHAUSTED = 8, FAILED_PRECONDITION = 9, ABORTED = 10,
OUT_OF_RANGE = 11, UNIMPLEMENTED = 12, INTERNAL = 13, UNAVAILABLE = 14,
DATA_LOSS = 15
}
Public Member Functions
status (status_code _error_code, std::string _msg)
status (status_code error_code)
bool is_ok () const
std::string to_string () const
Static Public Member Functions
static status aborted (std::string msg)
static status canceled (std::string msg)
static status data_loss (std::string msg)
static status failed_precondition (std::string msg)
static status internal (std::string msg)
static status invalid_argument (std::string msg)
static status not_found (std::string msg)
static status ok ()
static status ok (std::string msg)
static status out_of_range (std::string msg)
static status permission_denied (std::string msg)
static status resource_exhausted (std::string msg)
static status unavailable (std::string msg)
static status unimplemented (std::string msg)
static status unknown (std::string msg)
Public Attributes
status_code code
std::string msg
Member Enumeration Documentation
status_code
enum automaton::core::common::status::status_code
Enumerator
OK
CANCELLED
UNKNOWN
INVALID_ARGUMENT
DEADLINE_EXCEEDED
NOT_FOUND
ALREADY_EXISTS
PERMISSION_DENIED
UNAUTHENTICATED
RESOURCE_EXHAUSTED
FAILED_PRECONDITION
ABORTED
OUT_OF_RANGE
UNIMPLEMENTED
INTERNAL
UNAVAILABLE
DATA_LOSS
Constructor & Destructor Documentation
status() [1/2]
automaton::core::common::status::status (status_code error_code) inline explicit
Referenced by aborted(), canceled(), data_loss(), failed_precondition(), internal(), invalid_argument(), not_found(), ok(), out_of_range(), permission_denied(), resource_exhausted(), to_string(), unavailable(), unimplemented(), and unknown().
status() [2/2]
automaton::core::common::status::status (status_code _error_code, std::string _msg) inline
Member Function Documentation
aborted()
static status automaton::core::common::status::aborted (std::string msg) inline static
References status(), ABORTED, and msg.
canceled()
static status automaton::core::common::status::canceled (std::string msg) inline static
References status(), CANCELLED, and msg.
Referenced by automaton::core::node::node::connect().
data_loss()
static status automaton::core::common::status::data_loss (std::string msg) inline static
References status(), DATA_LOSS, and msg.
failed_precondition()
static status automaton::core::common::status::failed_precondition (std::string msg) inline static
References status(), FAILED_PRECONDITION, and msg.
Referenced by automaton::core::node::node::connect().
internal()
static status automaton::core::common::status::internal (std::string msg) inline static
References status(), INTERNAL, and msg.
invalid_argument()
static status automaton::core::common::status::invalid_argument (std::string msg) inline static
References status(), INVALID_ARGUMENT, and msg.
is_ok()
bool automaton::core::common::status::is_ok () const inline
References code, and OK.
not_found()
static status automaton::core::common::status::not_found (std::string msg) inline static
References status(), msg, and NOT_FOUND.
ok() [1/2]
static status automaton::core::common::status::ok () inline static
References status(), and OK.
ok() [2/2]
static status automaton::core::common::status::ok (std::string msg) inline static
References status(), msg, and OK.
out_of_range()
static status automaton::core::common::status::out_of_range (std::string msg) inline static
References status(), msg, and OUT_OF_RANGE.
permission_denied()
static status automaton::core::common::status::permission_denied (std::string msg) inline static
References status(), msg, and PERMISSION_DENIED.
resource_exhausted()
static status automaton::core::common::status::resource_exhausted (std::string msg) inline static
References status(), msg, and RESOURCE_EXHAUSTED.
to_string()
std::string automaton::core::common::status::to_string () const
References status().
unavailable()
static status automaton::core::common::status::unavailable (std::string msg) inline static
References status(), msg, and UNAVAILABLE.
unimplemented()
static status automaton::core::common::status::unimplemented (std::string msg) inline static
References status(), msg, and UNIMPLEMENTED.
unknown()
static status automaton::core::common::status::unknown (std::string msg) inline static
References status(), msg, and UNKNOWN.
Member Data Documentation
code
status_code automaton::core::common::status::code
Referenced by automaton::core::interop::ethereum::eth_contract::eth_contract(), automaton::core::interop::ethereum::eth_contract::call(), is_ok(), main(), client_handler::on_connection_error(), client_handler::on_message_sent(), and automaton::core::common::operator<<().
msg
std::string automaton::core::common::status::msg
Referenced by automaton::core::interop::ethereum::eth_contract::eth_contract(), aborted(), automaton::core::interop::ethereum::eth_contract::call(), canceled(), data_loss(), failed_precondition(), internal(), invalid_argument(), main(), not_found(), ok(), automaton::core::common::operator<<(), out_of_range(), permission_denied(), resource_exhausted(), unavailable(), unimplemented(), and unknown().
The documentation for this struct was generated from the following files:
status.h
status.cc