Automaton Core: automaton::core::node::default_node_updater Class Reference
automaton::core::node::default_node_updater Class Reference
#include <node_updater.h>
Public Member Functions
default_node_updater (uint32_t workers_number, uint32_t sleep_time, std::set< std::string > node_list)
~default_node_updater ()
void update_function ()
Public Member Functions inherited from automaton::core::node::node_updater
node_updater (uint32_t workers_number, uint32_t sleep_time, std::set< std::string > node_list)
virtual ~node_updater ()
void add_node (const std::string &node_id)
void remove_node (const std::string &node_id)
void start ()
void stop ()
Additional Inherited Members
Protected Attributes inherited from automaton::core::node::node_updater
std::set< std::string > node_list
bool running
Constructor & Destructor Documentation
default_node_updater()
automaton::core::node::default_node_updater::default_node_updater (uint32_t workers_number, uint32_t sleep_time, std::set< std::string > node_list)
~default_node_updater()
automaton::core::node::default_node_updater::~default_node_updater () inline
Member Function Documentation
update_function()
void automaton::core::node::default_node_updater::update_function () virtual
Implements automaton::core::node::node_updater.
References automaton::core::node::node::get_node(), automaton::core::node::node::get_time_to_update(), automaton::core::node::node_updater::node_list, automaton::core::node::node::process_update(), automaton::core::node::node_updater::remove_node(), automaton::core::node::node_updater::running, and automaton::core::interop::ethereum::string.
The documentation for this class was generated from the following files:
node_updater.h
node_updater.cc