Automaton Core: automaton::core::script::engine Class Reference
automaton::core::script::engine Class Reference
#include <engine.h>
Public Member Functions
engine ()
engine (std::shared_ptr< data::factory > data_factory)
~engine ()
void bind_core ()
void bind_crypto ()
void bind_data ()
void bind_io ()
void bind_log ()
void bind_network ()
void bind_state ()
std::shared_ptr< data::factory > get_factory ()
void import_schema (data::schema *msg_schema)
void set_factory (std::shared_ptr< data::factory > factory)
Detailed Description
Lua script engine wrapper and Autoamaton's module bridge.
Constructor & Destructor Documentation
engine() [1/2]
automaton::core::script::engine::engine ()
engine() [2/2]
automaton::core::script::engine::engine (std::shared_ptr< data::factory > data_factory) explicit
~engine()
automaton::core::script::engine::~engine ()
Member Function Documentation
bind_core()
void automaton::core::script::engine::bind_core () inline
References bind_crypto(), bind_data(), bind_io(), bind_log(), bind_network(), and bind_state().
Referenced by main().
bind_crypto()
void automaton::core::script::engine::bind_crypto ()
References CHECK_LT, and automaton::core::interop::ethereum::string.
Referenced by bind_core().
bind_data()
void automaton::core::script::engine::bind_data ()
References automaton::core::data::msg::get_blob(), automaton::core::data::msg::get_field_info_by_tag(), automaton::core::data::msg::get_field_tag(), automaton::core::data::msg::get_int32(), automaton::core::data::msg::get_int64(), automaton::core::data::msg::get_message(), automaton::core::data::msg::get_repeated_blob(), automaton::core::data::msg::get_repeated_field_size(), automaton::core::data::msg::get_repeated_int32(), automaton::core::data::msg::get_repeated_int64(), automaton::core::data::msg::get_repeated_message(), automaton::core::data::msg::get_repeated_uint32(), automaton::core::data::msg::get_repeated_uint64(), automaton::core::data::msg::get_uint32(), automaton::core::data::msg::get_uint64(), automaton::core::data::msg::serialize_message(), automaton::core::data::msg::set_blob(), automaton::core::data::msg::set_int32(), automaton::core::data::msg::set_int64(), automaton::core::data::msg::set_message(), automaton::core::data::msg::set_repeated_blob(), automaton::core::data::msg::set_repeated_int32(), automaton::core::data::msg::set_repeated_int64(), automaton::core::data::msg::set_repeated_message(), automaton::core::data::msg::set_repeated_uint32(), automaton::core::data::msg::set_repeated_uint64(), automaton::core::data::msg::set_uint32(), automaton::core::data::msg::set_uint64(), automaton::core::interop::ethereum::string, automaton::core::data::msg::to_json(), automaton::core::data::schema::field_info::type, and VLOG.
Referenced by bind_core().
bind_io()
void automaton::core::script::engine::bind_io ()
References automaton::core::io::bin2hex(), automaton::core::io::hex2bin(), and automaton::core::interop::ethereum::string.
Referenced by bind_core().
bind_log()
void automaton::core::script::engine::bind_log ()
Referenced by bind_core().
bind_network()
void automaton::core::script::engine::bind_network ()
Referenced by bind_core().
bind_state()
void automaton::core::script::engine::bind_state ()
Referenced by bind_core().
get_factory()
std::shared_ptr<data::factory> automaton::core::script::engine::get_factory () inline
Referenced by automaton::core::node::luanode::lua_node::create_msg_by_id(), and automaton::core::node::luanode::lua_node::find_message_id().
import_schema()
void automaton::core::script::engine::import_schema (data::schema * msg_schema)
References automaton::core::data::schema::get_message_names().
Referenced by main().
set_factory()
void automaton::core::script::engine::set_factory (std::shared_ptr< data::factory > factory)
Referenced by automaton::core::node::luanode::lua_node::init().
The documentation for this class was generated from the following files:
engine.h
bind_crypto.cc
bind_data.cc
engine.cc