Automaton Core: automaton::core::storage::blobstore Class Reference
automaton::core::storage::blobstore Class Reference
#include <blobstore.h>
Public Member Functions
blobstore ()
~blobstore ()
bool free (const uint32_t id)
uint8_t * get (const uint64_t id, uint32_t *size)
uint64_t store (const uint32_t size, const uint8_t *data)
Detailed Description
Blobstore interface. Can store and delete arbitrary length data in a memory mapped file. There are no protections. The pointer points to the internal memory.
Constructor & Destructor Documentation
blobstore()
automaton::core::storage::blobstore::blobstore ()
~blobstore()
automaton::core::storage::blobstore::~blobstore ()
Member Function Documentation
free()
bool automaton::core::storage::blobstore::free (const uint32_t id)
Frees allocated blob.
Returns
bool False if there is no allocated blob with the given id
Parameters
[in] id The ID returned by create_blob
get()
uint8_t * automaton::core::storage::blobstore::get (const uint64_t id, uint32_t * size)
Used to get access to previously allocated blob.
Returns
uint8_t* pointer to the blob or nullptr if id>=capacity
Parameters
[in] id The ID returned by create_blob
[out] size The size of the data pointed by the returned pointer in bytes
Referenced by automaton::core::state::state_persistent::node::get_hash(), automaton::core::state::state_persistent::node::get_parent(), automaton::core::state::state_persistent::node::get_prefix(), and automaton::core::state::state_persistent::node::get_value().
store()
uint64_t automaton::core::storage::blobstore::store (const uint32_t size, const uint8_t * data)
Stores the byte array pointed by data
Returns
uint64_t returns the ID used to access it.
Parameters
[in] size The size of the data pointed by data in bytes
[out] data Pointer to the data
Referenced by automaton::core::state::state_persistent::state_persistent(), automaton::core::state::state_persistent::node::set_hash(), automaton::core::state::state_persistent::node::set_parent(), automaton::core::state::state_persistent::node::set_prefix(), and automaton::core::state::state_persistent::node::set_value().
The documentation for this class was generated from the following files:
blobstore.h
blobstore.cc