Automaton Core: automaton::core::script::module Class Reference
automaton::core::script::module Class Reference abstract
#include <registry.h>
Classes
struct concept_info
struct implementation_info
struct method_info
struct static_function_info
Public Types
typedef std::unique_ptr< common::obj >(* constructor_function) (const data::msg &m)
typedef common::status(* module_static_function) (const data::msg &m, data::msg *output)
Public Member Functions
virtual const uint32_t api_version () const
virtual void bind_schemas ()
void check_implementation (const std::string implementation)
virtual const std::vector< std::string > concepts () const
virtual const std::vector< std::string > dependencies () const
virtual const std::string extra_version () const
virtual const std::string full_version () const
virtual const std::unordered_map< std::string, static_function_info > functions () const
virtual const std::unordered_map< std::string, implementation_info > implementations () const
virtual const uint32_t minor_version () const
virtual const std::string name () const
virtual const std::string name_with_api_version () const
virtual const uint32_t patch_version () const
virtual data::schema * schema () const =0
Protected Member Functions
module (const std::string name, const std::string version)
void add_concept (const std::string concept)
void add_dependency (const std::string dependency, uint32_t api_version)
void add_function (const std::string function_name, module_static_function func)
void add_implementation (const std::string implementation, const std::vector< std::string > concepts, constructor_function f)
Detailed Description
Module interface definition base class.
Member Typedef Documentation
constructor_function
typedef std::unique_ptr<common::obj>(* automaton::core::script::module::constructor_function) (const data::msg &m)
module_static_function
typedef common::status(* automaton::core::script::module::module_static_function) (const data::msg &m, data::msg *output)
Constructor & Destructor Documentation
module()
automaton::core::script::module::module (const std::string name, const std::string version) inline protected
References el::base::debug::StackTrace().
Member Function Documentation
add_concept()
void automaton::core::script::module::add_concept (const std::string concept) inline protected
add_dependency()
void automaton::core::script::module::add_dependency (const std::string dependency, uint32_t api_version) inline protected
References api_version(), and name_with_api_version().
add_function()
void automaton::core::script::module::add_function (const std::string function_name, module_static_function func) protected
References name().
add_implementation()
void automaton::core::script::module::add_implementation (const std::string implementation, const std::vector< std::string > concepts, constructor_function f) protected
References CHECK_GT, automaton::core::script::module::implementation_info::concepts, concepts(), automaton::core::script::module::implementation_info::constructor_schema_id, automaton::core::script::module::implementation_info::func, automaton::core::script::registry::get_factory(), automaton::core::script::registry::instance(), automaton::core::script::module::concept_info::name, automaton::core::script::module::implementation_info::name, and name().
api_version()
virtual const uint32_t automaton::core::script::module::api_version () const inline virtual
Referenced by add_dependency().
bind_schemas()
void automaton::core::script::module::bind_schemas () virtual
References automaton::core::script::registry::get_factory(), automaton::core::data::factory::get_nested_message_schema_id(), automaton::core::data::factory::get_nested_messages_number(), automaton::core::data::factory::get_schema_id(), automaton::core::data::factory::get_schema_name(), automaton::core::script::module::method_info::input_schema_id, automaton::core::script::registry::instance(), automaton::core::script::module::method_info::name, name_with_api_version(), and automaton::core::script::module::method_info::output_schema_id.
check_implementation()
void automaton::core::script::module::check_implementation (const std::string implementation)
References automaton::core::script::registry::get_factory(), automaton::core::data::factory::get_schema_id(), automaton::core::script::registry::instance(), and name_with_api_version().
concepts()
virtual const std::vector<std::string> automaton::core::script::module::concepts () const inline virtual
Referenced by add_implementation().
dependencies()
virtual const std::vector<std::string> automaton::core::script::module::dependencies () const inline virtual
extra_version()
virtual const std::string automaton::core::script::module::extra_version () const inline virtual
full_version()
virtual const std::string automaton::core::script::module::full_version () const inline virtual
functions()
virtual const std::unordered_map<std::string, static_function_info> automaton::core::script::module::functions () const inline virtual
implementations()
virtual const std::unordered_map<std::string, implementation_info> automaton::core::script::module::implementations () const inline virtual
minor_version()
virtual const uint32_t automaton::core::script::module::minor_version () const inline virtual
name()
virtual const std::string automaton::core::script::module::name () const inline virtual
Referenced by add_function(), and add_implementation().
name_with_api_version()
virtual const std::string automaton::core::script::module::name_with_api_version () const inline virtual
Referenced by add_dependency(), bind_schemas(), and check_implementation().
patch_version()
virtual const uint32_t automaton::core::script::module::patch_version () const inline virtual
schema()
virtual data::schema* automaton::core::script::module::schema () const pure virtual
The documentation for this class was generated from the following files:
registry.h
registry.cc