Automaton Core: automaton::core::state::state_persistent::node Class Reference
automaton::core::state::state_persistent::node Class Reference
#include <state_persistent.h>
Public Member Functions
uint32_t get_child (uint8_t child, storage::blobstore *bs)
std::string get_hash (storage::blobstore *bs)
uint32_t get_parent (storage::blobstore *bs)
std::string get_prefix (storage::blobstore *bs)
std::string get_value (storage::blobstore *bs)
void set_child (const uint8_t child, const uint32_t value, storage::blobstore *bs)
void set_hash (const std::string hash, storage::blobstore *bs)
void set_parent (uint32_t parent, storage::blobstore *bs)
void set_prefix (const std::string prefix, storage::blobstore *bs)
void set_value (const std::string value, storage::blobstore *bs)
Public Attributes
uint32_t children_ [256] = {}
uint64_t hash_ = 0
uint32_t parent_ = 0
uint64_t prefix_ = 0
uint64_t value_ = 0
Member Function Documentation
get_child()
uint32_t automaton::core::state::state_persistent::node::get_child (uint8_t child, storage::blobstore * bs)
get_hash()
std::string automaton::core::state::state_persistent::node::get_hash (storage::blobstore * bs)
References automaton::core::storage::blobstore::get(), and automaton::core::interop::ethereum::string.
get_parent()
uint32_t automaton::core::state::state_persistent::node::get_parent (storage::blobstore * bs)
References automaton::core::storage::blobstore::get(), and parent_.
get_prefix()
std::string automaton::core::state::state_persistent::node::get_prefix (storage::blobstore * bs)
References automaton::core::storage::blobstore::get(), and automaton::core::interop::ethereum::string.
get_value()
std::string automaton::core::state::state_persistent::node::get_value (storage::blobstore * bs)
References automaton::core::storage::blobstore::get(), and automaton::core::interop::ethereum::string.
set_child()
void automaton::core::state::state_persistent::node::set_child (const uint8_t child, const uint32_t value, storage::blobstore * bs)
set_hash()
void automaton::core::state::state_persistent::node::set_hash (const std::string hash, storage::blobstore * bs)
References automaton::core::eth_contract::hash(), and automaton::core::storage::blobstore::store().
set_parent()
void automaton::core::state::state_persistent::node::set_parent (uint32_t parent, storage::blobstore * bs)
References automaton::core::storage::blobstore::store().
set_prefix()
void automaton::core::state::state_persistent::node::set_prefix (const std::string prefix, storage::blobstore * bs)
References automaton::core::storage::blobstore::store().
set_value()
void automaton::core::state::state_persistent::node::set_value (const std::string value, storage::blobstore * bs)
References automaton::core::storage::blobstore::store().
Member Data Documentation
children_
uint32_t automaton::core::state::state_persistent::node::children_[256] = {}
hash_
uint64_t automaton::core::state::state_persistent::node::hash_ = 0
parent_
uint32_t automaton::core::state::state_persistent::node::parent_ = 0
Referenced by get_parent().
prefix_
uint64_t automaton::core::state::state_persistent::node::prefix_ = 0
value_
uint64_t automaton::core::state::state_persistent::node::value_ = 0
The documentation for this class was generated from the following files:
state_persistent.h
state_persistent.cc