Automaton Core: automaton::core::interop::ethereum::eth_transaction Class Reference
automaton::core::interop::ethereum::eth_transaction Class Reference
#include <eth_transaction.h>
Public Member Functions
std::string sign_tx (const std::string &private_key_hex)
Public Attributes
std::string chain_id
std::string data
std::string gas_limit
std::string gas_price
std::string nonce
std::string to
std::string value
Detailed Description
Ethereum transaction. Transaction fields should be given as hex strings WITHOUT '0x' prefix.
Member Function Documentation
sign_tx()
std::string automaton::core::interop::ethereum::eth_transaction::sign_tx (const std::string & private_key_hex)
Constructs and signs the transaction with the given in hex private_key then adds the signature and encode it in RLP. The result is the whole raw transaction in hex ready to be uploaded.
References automaton::core::io::bin2hex(), chain_id, automaton::core::io::dec2hex(), automaton::core::interop::ethereum::hash(), automaton::core::io::hex2bin(), automaton::core::io::hex2dec(), automaton::core::interop::ethereum::rlp_encode(), automaton::core::interop::ethereum::secp256k1_sign_and_verify(), and automaton::core::interop::ethereum::string.
Referenced by main().
Member Data Documentation
chain_id
std::string automaton::core::interop::ethereum::eth_transaction::chain_id
Referenced by main(), and sign_tx().
data
std::string automaton::core::interop::ethereum::eth_transaction::data
Referenced by main().
gas_limit
std::string automaton::core::interop::ethereum::eth_transaction::gas_limit
Referenced by main().
gas_price
std::string automaton::core::interop::ethereum::eth_transaction::gas_price
Referenced by main().
nonce
std::string automaton::core::interop::ethereum::eth_transaction::nonce
Referenced by main().
to
std::string automaton::core::interop::ethereum::eth_transaction::to
Referenced by main().
value
std::string automaton::core::interop::ethereum::eth_transaction::value
Referenced by main().
The documentation for this class was generated from the following files:
eth_transaction.h
eth_transaction.cc