Automaton Core: automaton::core::interop::ethereum Namespace Reference
automaton::core::interop::ethereum Namespace Reference
Classes
struct curl_struct
class eth_contract
class eth_transaction
struct type
Enumerations
enum abi_array_type { no_array = 0, fixed = 1, dynamic = 2 }
enum abi_type {
empty = 0, numerical = 1, fixed_size_bytes = 2, dynamic_size_bytes = 3,
string = 4
}
Functions
uint32_t calculate_offset (std::vector< std::string > params)
void check_and_resize_buffer (char **buffer, size_t *size, size_t pos, size_t data_size)
curl_struct * create_new_curl_struct (const std::string &url)
size_t curl_callback (void *contents, size_t size, size_t nmemb, std::string *s)
status curl_post (const std::string &url, const std::string &data, uint32_t call_id)
std::string dec_to_32hex (uint32_t n)
std::string dec_to_i256 (bool is_signed, std::string s)
std::string decode (const std::string &signatures_json, const std::string &data)
std::string decode_param (type t, const std::string &data, size_t pos)
void destroy_curl_struct (curl_struct *c_struct)
std::string encode (const std::string &signatures_json, const std::string &parameters_json)
void encode_param (type t, const json &json_data, char **buffer, size_t *buf_size, size_t *head_pos, size_t *tail_pos)
std::string encode_string (const std::string &byte_array)
status eth_gasPrice (const std::string &url)
status eth_getBalance (const std::string &url, const std::string &address)
status eth_getCode (const std::string &url, const std::string &address)
status eth_getTransactionCount (const std::string &url, const std::string &address)
status eth_getTransactionReceipt (const std::string &url, const std::string &tx_hash)
type extract_array_type (std::string s)
std::string get_address_from_prkey (const std::string &private_key_hex)
type get_type (std::string s)
status handle_result (const std::string &message, uint32_t call_id)
std::string hash (const std::string &data)
std::string i256_to_dec (bool is_signed, const std::string &s)
std::ostream & operator<< (std::ostream &os, const abi_type &obj)
std::ostream & operator<< (std::ostream &os, const type &obj)
std::string rlp_encode (std::string s, bool is_list)
std::string secp256k1_recover_address (const unsigned char *rsv, const unsigned char *message_hash)
std::string secp256k1_sign (const unsigned char *priv_key, const unsigned char *msg_hash)
std::string secp256k1_sign_and_verify (const unsigned char *priv_key, const unsigned char *message_hash)
uint64_t u256_to_u64 (const std::string &s)
std::string u64_to_u256 (uint64_t n)
Variables
static const uint32_t BUFFER_SIZE = 2048
static const uint32_t ERROR_BUF_SIZE = 1024
Enumeration Type Documentation
abi_array_type
enum automaton::core::interop::ethereum::abi_array_type
Enumerator
no_array
fixed
dynamic
abi_type
enum automaton::core::interop::ethereum::abi_type
Enumerator
empty
numerical
fixed_size_bytes
dynamic_size_bytes
string
Function Documentation
calculate_offset()
uint32_t automaton::core::interop::ethereum::calculate_offset (std::vector< std::string > params) inline
References automaton::core::interop::ethereum::type::array_len, extract_array_type(), fixed, get_type(), automaton::core::interop::ethereum::type::s_array_type, and automaton::core::interop::ethereum::type::str.
Referenced by decode(), decode_param(), encode(), and encode_param().
check_and_resize_buffer()
void automaton::core::interop::ethereum::check_and_resize_buffer (char ** buffer, size_t * size, size_t pos, size_t data_size) inline
References BUFFER_SIZE.
Referenced by encode(), and encode_param().
create_new_curl_struct()
curl_struct* automaton::core::interop::ethereum::create_new_curl_struct (const std::string & url) inline
References automaton::core::interop::ethereum::curl_struct::curl, curl_callback(), automaton::core::interop::ethereum::curl_struct::curl_err_buf, automaton::core::interop::ethereum::curl_struct::list, and automaton::core::interop::ethereum::curl_struct::msg_buf.
Referenced by curl_post().
curl_callback()
size_t automaton::core::interop::ethereum::curl_callback (void * contents, size_t size, size_t nmemb, std::string * s) inline
References string.
Referenced by create_new_curl_struct().
curl_post()
status automaton::core::interop::ethereum::curl_post (const std::string & url, const std::string & data, uint32_t call_id) inline
References create_new_curl_struct(), automaton::core::interop::ethereum::curl_struct::curl, automaton::core::interop::ethereum::curl_struct::curl_err_buf, destroy_curl_struct(), handle_result(), automaton::core::interop::ethereum::curl_struct::msg_buf, and string.
Referenced by automaton::core::interop::ethereum::eth_contract::call(), eth_gasPrice(), eth_getBalance(), eth_getCode(), eth_getTransactionCount(), and eth_getTransactionReceipt().
dec_to_32hex()
std::string automaton::core::interop::ethereum::dec_to_32hex (uint32_t n) inline
dec_to_i256()
std::string automaton::core::interop::ethereum::dec_to_i256 (bool is_signed, std::string s) inline
References automaton::tools::miner::sign(), and string.
Referenced by encode_param(), and main().
decode()
std::string automaton::core::interop::ethereum::decode (const std::string & signatures_json, const std::string & data) inline
References calculate_offset(), decode_param(), dynamic, dynamic_size_bytes, fixed, get_type(), string, and u256_to_u64().
decode_param()
std::string automaton::core::interop::ethereum::decode_param (type t, const std::string & data, size_t pos) inline
References automaton::core::interop::ethereum::type::array_len, automaton::core::io::bin2hex(), calculate_offset(), dynamic, dynamic_size_bytes, extract_array_type(), fixed, fixed_size_bytes, i256_to_dec(), no_array, numerical, automaton::core::interop::ethereum::type::s_array_type, automaton::core::interop::ethereum::type::s_type, automaton::core::interop::ethereum::type::str, string, and u256_to_u64().
Referenced by decode().
destroy_curl_struct()
void automaton::core::interop::ethereum::destroy_curl_struct (curl_struct * c_struct) inline
References automaton::core::interop::ethereum::curl_struct::curl, and automaton::core::interop::ethereum::curl_struct::list.
Referenced by curl_post().
encode()
std::string automaton::core::interop::ethereum::encode (const std::string & signatures_json, const std::string & parameters_json) inline
References BUFFER_SIZE, calculate_offset(), check_and_resize_buffer(), dynamic, dynamic_size_bytes, encode_param(), get_type(), automaton::core::interop::ethereum::type::s_array_type, automaton::core::interop::ethereum::type::s_type, string, and u64_to_u256().
Referenced by automaton::core::interop::ethereum::eth_contract::call().
encode_param()
void automaton::core::interop::ethereum::encode_param (type t, const json & json_data, char ** buffer, size_t * buf_size, size_t * head_pos, size_t * tail_pos) inline
References automaton::core::interop::ethereum::type::array_len, calculate_offset(), check_and_resize_buffer(), dec_to_i256(), dynamic, dynamic_size_bytes, encode_string(), extract_array_type(), fixed, fixed_size_bytes, automaton::core::io::hex2bin(), numerical, automaton::core::interop::ethereum::type::s_array_type, automaton::core::interop::ethereum::type::s_type, automaton::core::interop::ethereum::type::str, string, and u64_to_u256().
Referenced by encode().
encode_string()
std::string automaton::core::interop::ethereum::encode_string (const std::string & byte_array) inline
References string.
Referenced by encode_param().
eth_gasPrice()
status automaton::core::interop::ethereum::eth_gasPrice (const std::string & url) inline
References curl_post().
Referenced by automaton::core::interop::ethereum::eth_contract::eth_contract(), and main().
eth_getBalance()
status automaton::core::interop::ethereum::eth_getBalance (const std::string & url, const std::string & address) inline
References curl_post().
eth_getCode()
status automaton::core::interop::ethereum::eth_getCode (const std::string & url, const std::string & address) inline
References curl_post().
Referenced by main().
eth_getTransactionCount()
status automaton::core::interop::ethereum::eth_getTransactionCount (const std::string & url, const std::string & address) inline
References curl_post().
Referenced by main().
eth_getTransactionReceipt()
status automaton::core::interop::ethereum::eth_getTransactionReceipt (const std::string & url, const std::string & tx_hash) inline
References curl_post().
Referenced by automaton::core::interop::ethereum::eth_contract::call().
extract_array_type()
type automaton::core::interop::ethereum::extract_array_type (std::string s) inline
References get_type().
Referenced by calculate_offset(), decode_param(), and encode_param().
get_address_from_prkey()
std::string automaton::core::interop::ethereum::get_address_from_prkey (const std::string & private_key_hex) inline
References automaton::core::io::bin2hex(), hash(), automaton::core::io::hex2bin(), and string.
Referenced by automaton::core::interop::ethereum::eth_contract::call().
get_type()
type automaton::core::interop::ethereum::get_type (std::string s) inline
References automaton::core::interop::ethereum::type::array_len, dynamic, dynamic_size_bytes, fixed, fixed_size_bytes, no_array, numerical, automaton::core::interop::ethereum::type::s_array_type, automaton::core::interop::ethereum::type::s_type, automaton::core::interop::ethereum::type::str, and string.
Referenced by calculate_offset(), decode(), encode(), and extract_array_type().
handle_result()
status automaton::core::interop::ethereum::handle_result (const std::string & message, uint32_t call_id) inline
References string.
Referenced by curl_post().
hash()
std::string automaton::core::interop::ethereum::hash (const std::string & data) inline
Returns Keccak_256 hash of data as 32-byte string.
References automaton::core::crypto::cryptopp::Keccak_256_cryptopp::calculate_digest(), and string.
Referenced by get_address_from_prkey(), secp256k1_recover_address(), and automaton::core::interop::ethereum::eth_transaction::sign_tx().
i256_to_dec()
std::string automaton::core::interop::ethereum::i256_to_dec (bool is_signed, const std::string & s) inline
References automaton::tools::miner::sign(), and string.
Referenced by decode_param().
operator<<() [1/2]
std::ostream& automaton::core::interop::ethereum::operator<< (std::ostream & os, const abi_type & obj) inline
References dynamic_size_bytes, fixed_size_bytes, numerical, and string.
operator<<() [2/2]
std::ostream& automaton::core::interop::ethereum::operator<< (std::ostream & os, const type & obj) inline
References automaton::core::interop::ethereum::type::array_len, fixed, no_array, automaton::core::interop::ethereum::type::s_array_type, automaton::core::interop::ethereum::type::s_type, and automaton::core::interop::ethereum::type::str.
rlp_encode()
std::string automaton::core::interop::ethereum::rlp_encode (std::string s, bool is_list) inline
Returns RLP encoding of s in hex.
Parameters
[in] s data to be encode, MUST be in hex WITHOUT '0x' prefix.
[in] is_list shows if s represents one element or the payload of a list.
References automaton::core::io::dec2hex(), automaton::core::io::hex2dec(), and string.
Referenced by automaton::core::interop::ethereum::eth_transaction::sign_tx().
secp256k1_recover_address()
std::string automaton::core::interop::ethereum::secp256k1_recover_address (const unsigned char * rsv, const unsigned char * message_hash) inline
Returns recovered Ethereum address from a message and a signature.
References hash(), and string.
secp256k1_sign()
std::string automaton::core::interop::ethereum::secp256k1_sign (const unsigned char * priv_key, const unsigned char * msg_hash) inline
References string.
Referenced by secp256k1_sign_and_verify().
secp256k1_sign_and_verify()
std::string automaton::core::interop::ethereum::secp256k1_sign_and_verify (const unsigned char * priv_key, const unsigned char * message_hash) inline
Signs a message using secp256k1 also checks if a public key can be created from the given private key. If the check fails, empty string will be returned. Returns concatenated r, s and v values of the signature.
Parameters
[in] priv_key byte array repesenting the private key
[in] message_hash 32-byte string.
References automaton::core::io::bin2hex(), secp256k1_sign(), and string.
Referenced by automaton::core::interop::ethereum::eth_transaction::sign_tx().
u256_to_u64()
uint64_t automaton::core::interop::ethereum::u256_to_u64 (const std::string & s) inline
Referenced by decode(), and decode_param().
u64_to_u256()
std::string automaton::core::interop::ethereum::u64_to_u256 (uint64_t n) inline
References string.
Referenced by encode(), and encode_param().
Variable Documentation
BUFFER_SIZE
const uint32_t automaton::core::interop::ethereum::BUFFER_SIZE = 2048 static
Referenced by check_and_resize_buffer(), and encode().
ERROR_BUF_SIZE
const uint32_t automaton::core::interop::ethereum::ERROR_BUF_SIZE = 1024 static