Automaton Core: automaton::core::data::msg Class Reference
automaton::core::data::msg Class Reference abstract
#include <msg.h>
Public Member Functions
msg ()
msg (const msg &that)=delete
virtual ~msg ()=0
virtual bool deserialize_message (const std::string &input)=0
virtual bool from_json (const std::string &input)=0
virtual std::string get_blob (uint32_t field_tag) const =0
virtual bool get_boolean (uint32_t field_tag) const =0
virtual int32_t get_enum (uint32_t field_tag) const =0
virtual schema::field_info get_field_info_by_tag (uint32_t field_tag) const =0
virtual uint32_t get_field_tag (const std::string &name) const =0
virtual int32_t get_int32 (uint32_t field_tag) const =0
virtual int64_t get_int64 (uint32_t field_tag) const =0
virtual std::unique_ptr< msg > get_message (uint32_t field_tag) const =0
virtual std::string get_message_type () const =0
virtual std::string get_repeated_blob (uint32_t field_tag, int32_t index) const =0
virtual bool get_repeated_boolean (uint32_t field_tag, int32_t index) const =0
virtual int32_t get_repeated_enum (uint32_t field_tag, int32_t index) const =0
virtual uint32_t get_repeated_field_size (uint32_t field_tag) const =0
virtual int32_t get_repeated_int32 (uint32_t field_tag, int32_t index) const =0
virtual int64_t get_repeated_int64 (uint32_t field_tag, int32_t index) const =0
virtual std::unique_ptr< msg > get_repeated_message (uint32_t field_tag, int32_t index) const =0
virtual uint32_t get_repeated_uint32 (uint32_t field_tag, int32_t index) const =0
virtual uint64_t get_repeated_uint64 (uint32_t field_tag, int32_t index) const =0
virtual uint32_t get_schema_id () const =0
virtual uint32_t get_uint32 (uint32_t field_tag) const =0
virtual uint64_t get_uint64 (uint32_t field_tag) const =0
virtual bool serialize_message (std::string *output) const =0
virtual void set_blob (uint32_t field_tag, const std::string &value)=0
Blob (string, bytes, ...)
virtual void set_boolean (uint32_t field_tag, bool value)=0
Boolean.
virtual void set_enum (uint32_t field_tag, int32_t value)=0
virtual void set_int32 (uint32_t field_tag, int32_t value)=0
Int 32.
virtual void set_int64 (uint32_t field_tag, int64_t value)=0
Int 64.
virtual void set_message (uint32_t field_tag, const msg &sub_message)=0
virtual void set_repeated_blob (uint32_t field_tag, const std::string &value, int32_t index=-1)=0
virtual void set_repeated_boolean (uint32_t field_tag, bool value, int32_t index=-1)=0
virtual void set_repeated_enum (uint32_t field_tag, int32_t value, int32_t index=-1)=0
virtual void set_repeated_int32 (uint32_t field_tag, int32_t value, int32_t index=-1)=0
virtual void set_repeated_int64 (uint32_t field_tag, int64_t value, int32_t index=-1)=0
virtual void set_repeated_message (uint32_t field_tag, const msg &sub_message, int32_t index=-1)=0
virtual void set_repeated_uint32 (uint32_t field_tag, uint32_t value, int32_t index=-1)=0
virtual void set_repeated_uint64 (uint32_t field_tag, uint64_t value, int32_t index=-1)=0
virtual void set_uint32 (uint32_t field_tag, uint32_t value)=0
uint32_t 32
virtual void set_uint64 (uint32_t field_tag, uint64_t value)=0
uint32_t 64
virtual bool to_json (std::string *output) const =0
virtual std::string to_string () const =0
Detailed Description
Schema message interface
Constructor & Destructor Documentation
msg() [1/2]
automaton::core::data::msg::msg () inline
Referenced by automaton::core::data::protobuf::protobuf_msg::get_blob(), automaton::core::data::protobuf::protobuf_msg::get_boolean(), automaton::core::data::protobuf::protobuf_msg::get_enum(), automaton::core::data::protobuf::protobuf_msg::get_field_tag(), automaton::core::data::protobuf::protobuf_msg::get_int32(), automaton::core::data::protobuf::protobuf_msg::get_int64(), automaton::core::data::protobuf::protobuf_msg::get_message(), automaton::core::data::protobuf::protobuf_msg::get_repeated_blob(), automaton::core::data::protobuf::protobuf_msg::get_repeated_boolean(), automaton::core::data::protobuf::protobuf_msg::get_repeated_enum(), automaton::core::data::protobuf::protobuf_msg::get_repeated_field_size(), automaton::core::data::protobuf::protobuf_msg::get_repeated_int32(), automaton::core::data::protobuf::protobuf_msg::get_repeated_int64(), automaton::core::data::protobuf::protobuf_msg::get_repeated_message(), automaton::core::data::protobuf::protobuf_msg::get_repeated_uint32(), automaton::core::data::protobuf::protobuf_msg::get_repeated_uint64(), automaton::core::data::protobuf::protobuf_msg::get_uint32(), automaton::core::data::protobuf::protobuf_msg::get_uint64(), automaton::core::data::protobuf::protobuf_msg::set_blob(), automaton::core::data::protobuf::protobuf_msg::set_boolean(), automaton::core::data::protobuf::protobuf_msg::set_enum(), automaton::core::data::protobuf::protobuf_msg::set_int32(), automaton::core::data::protobuf::protobuf_msg::set_int64(), automaton::core::data::protobuf::protobuf_msg::set_message(), automaton::core::data::protobuf::protobuf_msg::set_repeated_blob(), automaton::core::data::protobuf::protobuf_msg::set_repeated_boolean(), automaton::core::data::protobuf::protobuf_msg::set_repeated_enum(), automaton::core::data::protobuf::protobuf_msg::set_repeated_int32(), automaton::core::data::protobuf::protobuf_msg::set_repeated_int64(), automaton::core::data::protobuf::protobuf_msg::set_repeated_message(), automaton::core::data::protobuf::protobuf_msg::set_repeated_uint32(), automaton::core::data::protobuf::protobuf_msg::set_repeated_uint64(), automaton::core::data::protobuf::protobuf_msg::set_uint32(), and automaton::core::data::protobuf::protobuf_msg::set_uint64().
msg() [2/2]
automaton::core::data::msg::msg (const msg & that) delete
~msg()
automaton::core::data::msg::~msg () pure virtual
Member Function Documentation
deserialize_message()
virtual bool automaton::core::data::msg::deserialize_message (const std::string & input) pure virtual
Deserializes message from the given string into a message with the given message id. If no such message exists or some error while deserializing happens, exception will be thrown. To use this function you should first create new message from the same schema and pass the id to this function.
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::node::node::get_wire_msg().
from_json()
virtual bool automaton::core::data::msg::from_json (const std::string & input) pure virtual
Deserializes message from JSON string.
Implemented in automaton::core::data::protobuf::protobuf_msg.
get_blob()
virtual std::string automaton::core::data::msg::get_blob (uint32_t field_tag) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
get_boolean()
virtual bool automaton::core::data::msg::get_boolean (uint32_t field_tag) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
get_enum()
virtual int32_t automaton::core::data::msg::get_enum (uint32_t field_tag) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
get_field_info_by_tag()
virtual schema::field_info automaton::core::data::msg::get_field_info_by_tag (uint32_t field_tag) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
get_field_tag()
virtual uint32_t automaton::core::data::msg::get_field_tag (const std::string & name) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
get_int32()
virtual int32_t automaton::core::data::msg::get_int32 (uint32_t field_tag) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
get_int64()
virtual int64_t automaton::core::data::msg::get_int64 (uint32_t field_tag) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
get_message()
virtual std::unique_ptr<msg> automaton::core::data::msg::get_message (uint32_t field_tag) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
get_message_type()
virtual std::string automaton::core::data::msg::get_message_type () const pure virtual
Returns the name of the message schema.
If schema with the given name doesn't exist, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::registry::create().
get_repeated_blob()
virtual std::string automaton::core::data::msg::get_repeated_blob (uint32_t field_tag, int32_t index) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
get_repeated_boolean()
virtual bool automaton::core::data::msg::get_repeated_boolean (uint32_t field_tag, int32_t index) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
get_repeated_enum()
virtual int32_t automaton::core::data::msg::get_repeated_enum (uint32_t field_tag, int32_t index) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
get_repeated_field_size()
virtual uint32_t automaton::core::data::msg::get_repeated_field_size (uint32_t field_tag) const pure virtual
Returns the size of the repeated field in the given message. If no such message or field exists or if the field is not repeated, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
get_repeated_int32()
virtual int32_t automaton::core::data::msg::get_repeated_int32 (uint32_t field_tag, int32_t index) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
get_repeated_int64()
virtual int64_t automaton::core::data::msg::get_repeated_int64 (uint32_t field_tag, int32_t index) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
get_repeated_message()
virtual std::unique_ptr<msg> automaton::core::data::msg::get_repeated_message (uint32_t field_tag, int32_t index) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
get_repeated_uint32()
virtual uint32_t automaton::core::data::msg::get_repeated_uint32 (uint32_t field_tag, int32_t index) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
get_repeated_uint64()
virtual uint64_t automaton::core::data::msg::get_repeated_uint64 (uint32_t field_tag, int32_t index) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
get_schema_id()
virtual uint32_t automaton::core::data::msg::get_schema_id () const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
get_uint32()
virtual uint32_t automaton::core::data::msg::get_uint32 (uint32_t field_tag) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
get_uint64()
virtual uint64_t automaton::core::data::msg::get_uint64 (uint32_t field_tag) const pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
serialize_message()
virtual bool automaton::core::data::msg::serialize_message (std::string * output) const pure virtual
Serializes the given message into the given string. If no such message exists or some error while serializing happens, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
set_blob()
virtual void automaton::core::data::msg::set_blob (uint32_t field_tag, const std::string & value) pure virtual
Blob (string, bytes, ...)
Setters and getters for the scalar types. If any tag or id is invalid, or if you try to use these functions on non-matching type fields, or if you try to use get/set_repeated_*() on non-repeated field or vise versa, exception will be thrown. If you use out of range index on set_repeated_*() the value will just be added at the end (not on the specified index). If you use out of range index on set_repeated_*(), exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
set_boolean()
virtual void automaton::core::data::msg::set_boolean (uint32_t field_tag, bool value) pure virtual
Boolean.
Implemented in automaton::core::data::protobuf::protobuf_msg.
set_enum()
virtual void automaton::core::data::msg::set_enum (uint32_t field_tag, int32_t value) pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
set_int32()
virtual void automaton::core::data::msg::set_int32 (uint32_t field_tag, int32_t value) pure virtual
Int 32.
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
set_int64()
virtual void automaton::core::data::msg::set_int64 (uint32_t field_tag, int64_t value) pure virtual
Int 64.
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
set_message()
virtual void automaton::core::data::msg::set_message (uint32_t field_tag, const msg & sub_message) pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
set_repeated_blob()
virtual void automaton::core::data::msg::set_repeated_blob (uint32_t field_tag, const std::string & value, int32_t index = -1) pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
set_repeated_boolean()
virtual void automaton::core::data::msg::set_repeated_boolean (uint32_t field_tag, bool value, int32_t index = -1) pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
set_repeated_enum()
virtual void automaton::core::data::msg::set_repeated_enum (uint32_t field_tag, int32_t value, int32_t index = -1) pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
set_repeated_int32()
virtual void automaton::core::data::msg::set_repeated_int32 (uint32_t field_tag, int32_t value, int32_t index = -1) pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
set_repeated_int64()
virtual void automaton::core::data::msg::set_repeated_int64 (uint32_t field_tag, int64_t value, int32_t index = -1) pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
set_repeated_message()
virtual void automaton::core::data::msg::set_repeated_message (uint32_t field_tag, const msg & sub_message, int32_t index = -1) pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
set_repeated_uint32()
virtual void automaton::core::data::msg::set_repeated_uint32 (uint32_t field_tag, uint32_t value, int32_t index = -1) pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
set_repeated_uint64()
virtual void automaton::core::data::msg::set_repeated_uint64 (uint32_t field_tag, uint64_t value, int32_t index = -1) pure virtual
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
set_uint32()
virtual void automaton::core::data::msg::set_uint32 (uint32_t field_tag, uint32_t value) pure virtual
uint32_t 32
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
set_uint64()
virtual void automaton::core::data::msg::set_uint64 (uint32_t field_tag, uint64_t value) pure virtual
uint32_t 64
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
to_json()
virtual bool automaton::core::data::msg::to_json (std::string * output) const pure virtual
Serializes message to JSON string.
Implemented in automaton::core::data::protobuf::protobuf_msg.
Referenced by automaton::core::script::engine::bind_data().
to_string()
virtual std::string automaton::core::data::msg::to_string () const pure virtual
Returns human readable representation of the message with the given id. If message id is not valid, exception will be thrown.
Implemented in automaton::core::data::protobuf::protobuf_msg.
The documentation for this class was generated from the following files:
msg.h
msg.cc