Automaton Core: automaton::core::network::connection::connection_handler Class Reference
automaton::core::network::connection::connection_handler Class Reference abstract
#include <connection.h>
Public Member Functions
virtual ~connection_handler ()
virtual void on_connected (connection_id c)=0
virtual void on_connection_error (connection_id c, const common::status &s)=0
virtual void on_disconnected (connection_id c)=0
virtual void on_message_received (connection_id c, std::shared_ptr< char > buffer, uint32_t bytes_read, uint32_t id)=0
virtual void on_message_sent (connection_id c, uint32_t id, const common::status &s)=0
Detailed Description
Handler class used to inform the client for events.
on_message_received will be invoked when message from remote peer was received; it passes the connection, representing from which peer was the message, and the message that was received.
on_message_sent will be invoked when a message was sent successfully using async_send.
on_connected will be invoked when the connection with the remote peer was established.
on_disconnected will be invoked when connection was closed/ destroyed by the local or the remote peer
on_error will be invoked when an error happens while listening or accepting.
Constructor & Destructor Documentation
~connection_handler()
virtual automaton::core::network::connection::connection_handler::~connection_handler () inline virtual
Member Function Documentation
on_connected()
virtual void automaton::core::network::connection::connection_handler::on_connected (connection_id c) pure virtual
Will be invoked to inform the user that a connection was successfully made after connect was called.
Parameters
[in] c the connection id
Referenced by automaton::core::network::tcp_connection::connect().
on_connection_error()
virtual void automaton::core::network::connection::connection_handler::on_connection_error (connection_id c, const common::status & s) pure virtual
Will be invoked when error occures in a connection to notify the user about the event.
Parameters
[in] c the id of the connection
[in] s status containing the error type and a description
See also
common::status
Referenced by automaton::core::network::tcp_connection::connect().
on_disconnected()
virtual void automaton::core::network::connection::connection_handler::on_disconnected (connection_id c) pure virtual
Will be invoked to inform the user that a disconnection was successfully made.
Parameters
[in] c the connection id
on_message_received()
virtual void automaton::core::network::connection::connection_handler::on_message_received (connection_id c, std::shared_ptr< char > buffer, uint32_t bytes_read, uint32_t id) pure virtual
Will be invoked to notify the user about a received message
Parameters
[in] c the id of the connection where the message was received
[in] buffer the buffer where the message is stored
[in] bytes_read the size of the received message
[in] id the identifier of the read operation
See also
connection::async_read
on_message_sent()
virtual void automaton::core::network::connection::connection_handler::on_message_sent (connection_id c, uint32_t id, const common::status & s) pure virtual
Will be invoked to notify the user that a message was successfully sent or an error occured.
Parameters
[in] c the id of the connection
[in] id the id of the message/send operation
See also
connection::async_send
Parameters
[in] s the status of the operation. If it was not successful s will contain the error and a description, s = status::ok, otherwise
See also
common::status
Referenced by automaton::core::network::tcp_connection::async_send().
The documentation for this class was generated from the following file:
connection.h