Automaton Core: rpc_server_core_test.cc File Reference
rpc_server_core_test.cc File Reference
#include <memory>
#include <string>
#include "automaton/core/network/tcp_implementation.h"
Classes
class client_handler
Functions
void client ()
int main (int argc, char *argv[])
Variables
std::shared_ptr< char > buffer_c = std::shared_ptr<char>(new char[256], std::default_delete<char[]>())
std::shared_ptr< connection > connection_c
std::shared_ptr< client_handler > handler_c
static const char * SERVER_ADDRESS = "127.0.0.1:33777"
Function Documentation
client()
void client ()
References buffer_c, connection_c, automaton::core::network::connection::create(), handler_c, SERVER_ADDRESS, and automaton::core::interop::ethereum::string.
Referenced by main().
main()
int main (int argc, char * argv[])
References client(), automaton::core::network::tcp_init(), and automaton::core::network::tcp_release().
Variable Documentation
buffer_c
std::shared_ptr<char> buffer_c = std::shared_ptr<char>(new char[256], std::default_delete<char[]>())
Referenced by client().
connection_c
std::shared_ptr<connection> connection_c
Referenced by client(), and client_handler::on_message_received().
handler_c
std::shared_ptr<client_handler> handler_c
Referenced by client().
SERVER_ADDRESS
const char* SERVER_ADDRESS = "127.0.0.1:33777" static
Referenced by client().