Automaton Core: automaton::core::network::http_server Class Reference
automaton::core::network::http_server Class Reference
#include <http_server.h>
Classes
class server_handler
Public Types
enum status_code {
OK = 0, NO_CONTENT = 1, BAD_REQUEST = 2, UNAUTHORIZED = 3,
FORBIDDEN = 4, INTERNAL_SERVER_ERROR = 5, NOT_IMPLEMENTED = 6, SERVICE_UNAVAILABLE = 7
}
Public Member Functions
http_server (uint16_t port, std::shared_ptr< server_handler >)
void handle_accept (http_session *new_session, const boost::system::error_code &error)
void run ()
void stop ()
Static Public Attributes
static const char * bad_request = "HTTP/1.0 400 Bad Request\r\n"
static const char * forbidden = "HTTP/1.0 403 Forbidden\r\n"
static const char * internal_server_error = "HTTP/1.0 500 Internal Server Error\r\n"
static const char * no_content = "HTTP/1.0 204 No Content\r\n"
static const char * not_implemented = "HTTP/1.0 501 Not Implemented\r\n"
static const char * ok = "HTTP/1.0 200 OK\r\n"
static const char * service_unavailable = "HTTP/1.0 503 Service Unavailable\r\n"
static const std::map< uint32_t, const char * > status_to_string
static const char * unauthorized = "HTTP/1.0 401 Unauthorized\r\n"
Member Enumeration Documentation
status_code
enum automaton::core::network::http_server::status_code
Enumerator
OK
NO_CONTENT
BAD_REQUEST
UNAUTHORIZED
FORBIDDEN
INTERNAL_SERVER_ERROR
NOT_IMPLEMENTED
SERVICE_UNAVAILABLE
Constructor & Destructor Documentation
http_server()
automaton::core::network::http_server::http_server (uint16_t port, std::shared_ptr< server_handler > sh)
References handle_accept(), and automaton::core::network::http_session::socket().
Member Function Documentation
handle_accept()
void automaton::core::network::http_server::handle_accept (http_session * new_session, const boost::system::error_code & error)
References automaton::core::network::http_session::socket(), and automaton::core::network::http_session::start().
Referenced by http_server().
run()
void automaton::core::network::http_server::run ()
Referenced by main().
stop()
void automaton::core::network::http_server::stop ()
Referenced by main().
Member Data Documentation
bad_request
const char * automaton::core::network::http_server::bad_request = "HTTP/1.0 400 Bad Request\r\n" static
forbidden
const char * automaton::core::network::http_server::forbidden = "HTTP/1.0 403 Forbidden\r\n" static
internal_server_error
const char * automaton::core::network::http_server::internal_server_error = "HTTP/1.0 500 Internal Server Error\r\n" static
no_content
const char * automaton::core::network::http_server::no_content = "HTTP/1.0 204 No Content\r\n" static
not_implemented
const char * automaton::core::network::http_server::not_implemented = "HTTP/1.0 501 Not Implemented\r\n" static
ok
const char * automaton::core::network::http_server::ok = "HTTP/1.0 200 OK\r\n" static
service_unavailable
const char * automaton::core::network::http_server::service_unavailable = "HTTP/1.0 503 Service Unavailable\r\n" static
status_to_string
const std::map< uint32_t, const char * > automaton::core::network::http_server::status_to_string static
Initial value:
{
  {OK, ok},
  {NO_CONTENT, no_content},
  {BAD_REQUEST, bad_request},
  {UNAUTHORIZED, unauthorized},
  {FORBIDDEN, forbidden},
  {INTERNAL_SERVER_ERROR, internal_server_error},
  {NOT_IMPLEMENTED, not_implemented},
  {SERVICE_UNAVAILABLE, service_unavailable}
}
unauthorized
const char * automaton::core::network::http_server::unauthorized = "HTTP/1.0 401 Unauthorized\r\n" static
The documentation for this class was generated from the following files:
http_server.h
http_server.cc