Automaton Core: automaton::core::node::node Class Reference
automaton::core::node::node Class Reference abstract
#include <node.h>
Public Types
typedef std::shared_ptr< node >(* factory_function) (const std::string &id, const std::string &proto_id)
Public Member Functions
~node ()
peer_id add_peer (const std::string &address)
bool connect (peer_id id)
bool disconnect (peer_id id)
void dump_logs (const std::string &html_file)
std::shared_ptr< network::acceptor > get_acceptor ()
std::string get_id () const
peer_info get_peer_info (peer_id id)
std::string get_protocol_id () const
uint64_t get_time_to_update ()
virtual void init ()=0
std::set< peer_id > list_connected_peers ()
std::vector< peer_id > list_known_peers ()
void log (const std::string &logger, const std::string &msg)
virtual std::string process_cmd (const std::string &cmd, const std::string &params)
void process_update (uint64_t current_time)
void remove_peer (peer_id id)
virtual void script (const std::string &command, std::promise< std::string > *result)
void send_blob (peer_id id, const std::string &blob, uint32_t msg_id)
void send_message (peer_id id, const data::msg &msg, uint32_t msg_id)
bool set_acceptor (const std::string &address)
bool set_peer_info (peer_id id, const peer_info &info)
Public Member Functions inherited from automaton::core::network::connection::connection_handler
virtual ~connection_handler ()
Public Member Functions inherited from automaton::core::network::acceptor::acceptor_handler
virtual ~acceptor_handler ()
Static Public Member Functions
static std::shared_ptr< node > create (const std::string &type, const std::string &id, const std::string &proto_id)
static std::shared_ptr< node > get_node (const std::string &node_id)
static bool launch_node (const std::string &node_type, const std::string &node_id, const std::string &protocol_id, const std::string &address)
static std::vector< std::string > list_nodes ()
static void register_node_type (const std::string &type, factory_function func)
static void remove_node (const std::string &node_id)
Protected Member Functions
node (const std::string &id, const std::string &proto_id)
void add_task (std::function< std::string()> task)
std::unique_ptr< data::msg > create_msg_by_id (uint32_t id, std::shared_ptr< data::factory > factory)
uint32_t find_message_id (const std::string &name, std::shared_ptr< data::factory > factory)
std::unique_ptr< data::msg > get_wire_msg (const std::string &blob)
Protected Attributes
std::string nodeid
std::string protoid
std::mutex script_mutex
Member Typedef Documentation
factory_function
typedef std::shared_ptr<node>(* automaton::core::node::node::factory_function) (const std::string &id, const std::string &proto_id)
Constructor & Destructor Documentation
~node()
automaton::core::node::node::~node ()
node()
automaton::core::node::node::node (const std::string & id, const std::string & proto_id) protected
References automaton::core::smartproto::smart_protocol::get_protocol().
Member Function Documentation
add_peer()
peer_id automaton::core::node::node::add_peer (const std::string & address)
Referenced by automaton::core::testnet::testnet::connect().
add_task()
void automaton::core::node::node::add_task (std::function< std::string()> task) protected
Referenced by automaton::core::node::luanode::lua_node::script().
connect()
bool automaton::core::node::node::connect (peer_id id)
References automaton::core::common::status::canceled(), automaton::core::common::status::failed_precondition(), automaton::core::node::MAX_MESSAGE_SIZE, and automaton::core::interop::ethereum::string.
Referenced by automaton::core::testnet::testnet::connect().
create()
std::shared_ptr< node > automaton::core::node::node::create (const std::string & type, const std::string & id, const std::string & proto_id) static
Referenced by launch_node().
create_msg_by_id()
std::unique_ptr< data::msg > automaton::core::node::node::create_msg_by_id (uint32_t id, std::shared_ptr< data::factory > factory) protected
Referenced by automaton::core::node::luanode::lua_node::create_msg_by_id().
disconnect()
bool automaton::core::node::node::disconnect (peer_id id)
dump_logs()
void automaton::core::node::node::dump_logs (const std::string & html_file)
find_message_id()
uint32_t automaton::core::node::node::find_message_id (const std::string & name, std::shared_ptr< data::factory > factory) protected
Referenced by automaton::core::node::luanode::lua_node::find_message_id().
get_acceptor()
std::shared_ptr< network::acceptor > automaton::core::node::node::get_acceptor ()
Referenced by main().
get_id()
string automaton::core::node::node::get_id () const
References nodeid.
get_node()
std::shared_ptr< node > automaton::core::node::node::get_node (const std::string & node_id) static
Referenced by automaton::core::testnet::testnet::connect(), automaton::core::node::default_node_updater::update_function(), and automaton::core::node::node_updater_tests::update_function().
get_peer_info()
peer_info automaton::core::node::node::get_peer_info (peer_id id)
Referenced by main().
get_protocol_id()
string automaton::core::node::node::get_protocol_id () const
References protoid.
get_time_to_update()
uint64_t automaton::core::node::node::get_time_to_update ()
Referenced by automaton::core::node::default_node_updater::update_function().
get_wire_msg()
std::unique_ptr< msg > automaton::core::node::node::get_wire_msg (const std::string & blob) protected
References CHECK_GT, and automaton::core::data::msg::deserialize_message().
init()
virtual void automaton::core::node::node::init () pure virtual
Implemented in automaton::core::node::luanode::lua_node.
launch_node()
bool automaton::core::node::node::launch_node (const std::string & node_type, const std::string & node_id, const std::string & protocol_id, const std::string & address) static
References create().
list_connected_peers()
std::set< peer_id > automaton::core::node::node::list_connected_peers ()
Referenced by main().
list_known_peers()
vector< peer_id > automaton::core::node::node::list_known_peers ()
Referenced by main().
list_nodes()
vector< string > automaton::core::node::node::list_nodes () static
log()
void automaton::core::node::node::log (const std::string & logger, const std::string & msg)
References automaton::core::io::get_date_string(), and automaton::core::io::zero_padded().
Referenced by process_update().
process_cmd()
virtual std::string automaton::core::node::node::process_cmd (const std::string & cmd, const std::string & params) inline virtual
Reimplemented in automaton::core::node::luanode::lua_node.
process_update()
void automaton::core::node::node::process_update (uint64_t current_time)
References log().
Referenced by automaton::core::node::default_node_updater::update_function(), and automaton::core::node::node_updater_tests::update_function().
register_node_type()
void automaton::core::node::node::register_node_type (const std::string & type, factory_function func) static
remove_node()
void automaton::core::node::node::remove_node (const std::string & node_id) static
Referenced by automaton::core::testnet::testnet::~testnet().
remove_peer()
void automaton::core::node::node::remove_peer (peer_id id)
script()
virtual void automaton::core::node::node::script (const std::string & command, std::promise< std::string > * result) inline virtual
Reimplemented in automaton::core::node::luanode::lua_node.
send_blob()
void automaton::core::node::node::send_blob (peer_id id, const std::string & blob, uint32_t msg_id)
send_message()
void automaton::core::node::node::send_message (peer_id id, const data::msg & msg, uint32_t msg_id)
set_acceptor()
bool automaton::core::node::node::set_acceptor (const std::string & address)
set_peer_info()
bool automaton::core::node::node::set_peer_info (peer_id id, const peer_info & info)
Member Data Documentation
nodeid
std::string automaton::core::node::node::nodeid protected
Referenced by get_id().
protoid
std::string automaton::core::node::node::protoid protected
Referenced by get_protocol_id(), and automaton::core::node::luanode::lua_node::init().
script_mutex
std::mutex automaton::core::node::node::script_mutex protected
Referenced by automaton::core::node::luanode::lua_node::process_cmd().
The documentation for this class was generated from the following files:
node.h
node.cc