Automaton Core: automaton::core::io::blob Struct Reference
automaton::core::io::blob Struct Reference
#include <blob.h>
Public Member Functions
blob (size_t size)
~blob ()
uint8_t get (size_t key)
void resize (size_t new_size)
void set (size_t key, int value)
size_t size ()
std::string tostring ()
Public Attributes
std::vector< uint8_t > buffer
Constructor & Destructor Documentation
blob()
automaton::core::io::blob::blob (size_t size) inline explicit
References resize(), and size().
~blob()
automaton::core::io::blob::~blob () inline
Member Function Documentation
get()
uint8_t automaton::core::io::blob::get (size_t key) inline
References buffer.
resize()
void automaton::core::io::blob::resize (size_t new_size) inline
References buffer.
Referenced by blob().
set()
void automaton::core::io::blob::set (size_t key, int value) inline
References buffer, and CHECK_GT.
size()
size_t automaton::core::io::blob::size () inline
References buffer.
Referenced by blob().
tostring()
std::string automaton::core::io::blob::tostring () inline
References automaton::core::io::bin2hex(), buffer, and automaton::core::interop::ethereum::string.
Member Data Documentation
buffer
std::vector<uint8_t> automaton::core::io::blob::buffer
Referenced by get(), resize(), set(), size(), and tostring().
The documentation for this struct was generated from the following file:
blob.h