Automaton Core: automaton::core::eth_contract Namespace Reference
automaton::core::eth_contract Namespace Reference
Classes
class eth_contract
Functions
std::string dec_to_32hex (uint32_t n)
std::string hash (const std::string &data)
uint32_t hex_to_dec (const std::string &hex)
Function Documentation
dec_to_32hex()
std::string automaton::core::eth_contract::dec_to_32hex (uint32_t n)
Referenced by main().
hash()
std::string automaton::core::eth_contract::hash (const std::string & data)
References automaton::core::crypto::cryptopp::Keccak_256_cryptopp::calculate_digest(), and automaton::core::interop::ethereum::string.
Referenced by automaton::core::state::state_persistent::node::set_hash().
hex_to_dec()
uint32_t automaton::core::eth_contract::hex_to_dec (const std::string & hex)