Automaton Core: automaton::core::data::protobuf::protobuf_factory Class Reference
automaton::core::data::protobuf::protobuf_factory Class Reference
#include <protobuf_factory.h>
Public Member Functions
protobuf_factory ()
~protobuf_factory ()
uint32_t create_copy_message (int32_t message_id)
std::string dump_enum (uint32_t enum_id) const
std::string dump_message_schema (uint32_t schema_id) const
std::string get_enum_field_type (uint32_t schema_id, uint32_t tag) const
uint32_t get_enum_id (const std::string &enum_name) const
int32_t get_enum_value (uint32_t enum_id, const std::string &value_name) const
std::vector< std::pair< std::string, int32_t > > get_enum_values (uint32_t enum_id) const
uint32_t get_enums_number () const
schema::field_info get_field_info (uint32_t schema_id, uint32_t index) const
uint32_t get_field_tag (uint32_t schema_id, const std::string &name) const
std::string get_field_type (uint32_t schema_id, uint32_t tag) const
uint32_t get_fields_number (uint32_t schema_id) const
std::string get_message_field_type (uint32_t schema_id, uint32_t tag) const
uint32_t get_message_schema_id (int32_t message_id) const
uint32_t get_nested_message_schema_id (uint32_t schema_id, uint32_t index) const
uint32_t get_nested_messages_number (uint32_t schema_id) const
uint32_t get_schema_id (const std::string &schema_name) const
std::string get_schema_name (uint32_t schema_id) const
uint32_t get_schemas_number () const
void import_schema (schema *schema, const std::string &name, const std::string &package)
bool is_repeated (uint32_t schema_id, uint32_t tag) const
std::unique_ptr< msg > new_message_by_id (uint32_t schema_id)
std::unique_ptr< msg > new_message_by_name (const char *schema_name)
Public Member Functions inherited from automaton::core::data::factory
virtual ~factory ()=0
Static Public Attributes
static const std::map< google::protobuf::FieldDescriptor::CppType, schema::field_type > protobuf_ccptype_to_type
static const std::map< google::protobuf::FieldDescriptor::Type, schema::field_type > protobuf_type_to_type
static const std::map< schema::field_type, google::protobuf::FieldDescriptorProto_Type > type_to_protobuf_type
Constructor & Destructor Documentation
protobuf_factory()
automaton::core::data::protobuf::protobuf_factory::protobuf_factory ()
TODO(kari): Decide to forbid move & copy constructors.
~protobuf_factory()
automaton::core::data::protobuf::protobuf_factory::~protobuf_factory ()
Member Function Documentation
create_copy_message()
uint32_t automaton::core::data::protobuf::protobuf_factory::create_copy_message (int32_t message_id)
dump_enum()
std::string automaton::core::data::protobuf::protobuf_factory::dump_enum (uint32_t enum_id) const virtual
following functions are too complicated for mvp.
Implements automaton::core::data::factory.
References CHECK_LT, and CHECK_NOTNULL.
dump_message_schema()
std::string automaton::core::data::protobuf::protobuf_factory::dump_message_schema (uint32_t schema_id) const virtual
Prints information about a message schema and its fields. If the given schema id is not valid, exception will be thrown.
Implements automaton::core::data::factory.
References CHECK_LT, CHECK_NOTNULL, and protobuf_type_to_type.
get_enum_field_type()
string automaton::core::data::protobuf::protobuf_factory::get_enum_field_type (uint32_t schema_id, uint32_t tag) const virtual
If the type of the field is enum, returns the fully-qualified name of the enum type. If the given schema id is not valid or if there is no field with the given tag or the field type is not enum, exception will be thrown.
Implements automaton::core::data::factory.
References CHECK_LT, CHECK_NOTNULL, and el::base::debug::StackTrace().
get_enum_id()
uint32_t automaton::core::data::protobuf::protobuf_factory::get_enum_id (const std::string & enum_name) const virtual
Get the id of the enum with enum_name. Id is needed for getting information about the enum values. If enum with the given name doesn't exist, exception will be thrown.
Implements automaton::core::data::factory.
References el::base::debug::StackTrace().
get_enum_value()
int32_t automaton::core::data::protobuf::protobuf_factory::get_enum_value (uint32_t enum_id, const std::string & value_name) const virtual
Returns enum value matching value name. If no such enum or name exists, exception will be thrown.
Implements automaton::core::data::factory.
References CHECK_LT, CHECK_NOTNULL, and el::base::debug::StackTrace().
get_enum_values()
std::vector< std::pair< string, int32_t > > automaton::core::data::protobuf::protobuf_factory::get_enum_values (uint32_t enum_id) const virtual
Returns a vector of pairs containing info about the values in this enum. A pair represents the string name of the value and the int value. If no such enum exists, exception will be thrown.
Implements automaton::core::data::factory.
References CHECK_LT, and CHECK_NOTNULL.
get_enums_number()
uint32_t automaton::core::data::protobuf::protobuf_factory::get_enums_number () const virtual
Returns the number of enums in the whole schema definition (both top-level and nested).
Implements automaton::core::data::factory.
get_field_info()
schema::field_info automaton::core::data::protobuf::protobuf_factory::get_field_info (uint32_t schema_id, uint32_t index) const virtual
Returns info about the specified field. Index must be >= 0 and < get_fields_number(schema_id). If no such schema or such field exists, exception will be thrown.
Implements automaton::core::data::factory.
References CHECK_LT, CHECK_NOTNULL, automaton::core::data::schema::enum_type, automaton::core::data::schema::message_type, protobuf_ccptype_to_type, and el::base::debug::StackTrace().
get_field_tag()
uint32_t automaton::core::data::protobuf::protobuf_factory::get_field_tag (uint32_t schema_id, const std::string & name) const virtual
Returns the tag of the field with the given name in the schema with the given id. If the given schema id is not valid or there is no field with the given name, exception will be thrown.
Implements automaton::core::data::factory.
References CHECK_LT, CHECK_NOTNULL, and el::base::debug::StackTrace().
get_field_type()
string automaton::core::data::protobuf::protobuf_factory::get_field_type (uint32_t schema_id, uint32_t tag) const virtual
Returns the type (as a string) of the field with the given tag in the schema with the given id. If the given schema id is not valid or there is no field with the given tag, exception will be thrown.
If the type is message, returns 'message'. To get the type of a message field use get_message_field_type().
If the type is enum, returns 'enum'. To get the type of a enum field use get_enum_field_type().
Use the result of this function in set_*() and get_*() and in set_repeated_*() and get_repeated_*() if the field is repeated.
Implements automaton::core::data::factory.
References CHECK_LT, CHECK_NOTNULL, el::base::debug::StackTrace(), and automaton::core::interop::ethereum::string.
get_fields_number()
uint32_t automaton::core::data::protobuf::protobuf_factory::get_fields_number (uint32_t schema_id) const virtual
Returns the number of fields in the schema with the given id. If no such schema exists, exception will be thrown.
Implements automaton::core::data::factory.
References CHECK_LT, and CHECK_NOTNULL.
get_message_field_type()
string automaton::core::data::protobuf::protobuf_factory::get_message_field_type (uint32_t schema_id, uint32_t tag) const virtual
If the type of the field is message, returns the fully-qualified name of the message type. If the given schema id is not valid or if there is no field with the given tag or the field type is not message, exception will be thrown.
Implements automaton::core::data::factory.
References CHECK_LT, CHECK_NOTNULL, and el::base::debug::StackTrace().
get_message_schema_id()
uint32_t automaton::core::data::protobuf::protobuf_factory::get_message_schema_id (int32_t message_id) const
get_nested_message_schema_id()
uint32_t automaton::core::data::protobuf::protobuf_factory::get_nested_message_schema_id (uint32_t schema_id, uint32_t index) const virtual
Returns the schema id of the corresponding nested message.
Implements automaton::core::data::factory.
References CHECK_LT, CHECK_NOTNULL, and get_schema_id().
get_nested_messages_number()
uint32_t automaton::core::data::protobuf::protobuf_factory::get_nested_messages_number (uint32_t schema_id) const virtual
Returns the number of nested message types in the specified message schema.
Implements automaton::core::data::factory.
References CHECK_LT, and CHECK_NOTNULL.
get_schema_id()
uint32_t automaton::core::data::protobuf::protobuf_factory::get_schema_id (const std::string & schema_name) const virtual
Returns the id of the schema with schema_name. Id is needed for creating new messages of that type, also getting information about the fields. If schema with the given name doesn't exist, exception will be thrown.
Implements automaton::core::data::factory.
References el::base::debug::StackTrace().
Referenced by get_nested_message_schema_id(), and new_message_by_name().
get_schema_name()
string automaton::core::data::protobuf::protobuf_factory::get_schema_name (uint32_t schema_id) const virtual
Returns the name of the schema of message with the given id. If schema with the given name doesn't exist, exception will be thrown.
Implements automaton::core::data::factory.
References CHECK_LT, and CHECK_NOTNULL.
get_schemas_number()
uint32_t automaton::core::data::protobuf::protobuf_factory::get_schemas_number () const virtual
Returns the number of messages in the whole schema definition (both top-level and nested).
Implements automaton::core::data::factory.
import_schema()
void automaton::core::data::protobuf::protobuf_factory::import_schema (schema * schema, const std::string & name, const std::string & package) virtual
This function is used for include schema definitions that were created with schema. If the given schema has dependencies, they must be imported first or exception will be thrown. Name will be used for reference in schema::add_dependency(). Package is used in fully_qualified_type.
Implements automaton::core::data::factory.
References CHECK_NOTNULL, automaton::core::interop::ethereum::string, and automaton::core::data::schema::to_json().
is_repeated()
bool automaton::core::data::protobuf::protobuf_factory::is_repeated (uint32_t schema_id, uint32_t tag) const virtual
Returns true if the field is repeated, false, otherwise. If the given schema id is not valid or if there is no field with the given tag, exception will be thrown.
Implements automaton::core::data::factory.
References CHECK_LT, CHECK_NOTNULL, and el::base::debug::StackTrace().
new_message_by_id()
std::unique_ptr< msg > automaton::core::data::protobuf::protobuf_factory::new_message_by_id (uint32_t message_type_id) virtual
Creates new message from a schema with message_type_id. Returns the created message that is used for setting and getting data, serializing and deserializing, etc.
If the given message_type_id is not valid, exception will be thrown.
Implements automaton::core::data::factory.
References CHECK_LT, and CHECK_NOTNULL.
Referenced by new_message_by_name().
new_message_by_name()
std::unique_ptr< msg > automaton::core::data::protobuf::protobuf_factory::new_message_by_name (const char * schema_name) virtual
Creates new message from a schema name.
Returns the created message that is used for setting and getting data, serializing and deserializing, etc.
If the given schema_name is not valid, exception will be thrown.
Implements automaton::core::data::factory.
References get_schema_id(), and new_message_by_id().
Member Data Documentation
protobuf_ccptype_to_type
const std::map< FieldDescriptor::CppType, schema::field_type > automaton::core::data::protobuf::protobuf_factory::protobuf_ccptype_to_type static
Initial value:
{
  {FieldDescriptor::CPPTYPE_STRING, schema::blob},
  {FieldDescriptor::CPPTYPE_BOOL, schema::boolean},
  {FieldDescriptor::CPPTYPE_INT32, schema::int32},
  {FieldDescriptor::CPPTYPE_UINT32, schema::uint32},
  {FieldDescriptor::CPPTYPE_INT64, schema::int64},
  {FieldDescriptor::CPPTYPE_UINT64, schema::uint64},
  {FieldDescriptor::CPPTYPE_ENUM, schema::enum_type},
  {FieldDescriptor::CPPTYPE_MESSAGE, schema::message_type},
}
Referenced by get_field_info(), and automaton::core::data::protobuf::protobuf_msg::get_field_info_by_tag().
protobuf_type_to_type
const std::map< FieldDescriptor::Type, schema::field_type > automaton::core::data::protobuf::protobuf_factory::protobuf_type_to_type static
Initial value:
{
  {FieldDescriptor::TYPE_STRING, schema::blob},
  {FieldDescriptor::TYPE_BYTES, schema::blob},
  {FieldDescriptor::TYPE_BOOL, schema::boolean},
  {FieldDescriptor::TYPE_INT32, schema::int32},
  {FieldDescriptor::TYPE_SINT32, schema::int32},
  {FieldDescriptor::TYPE_SFIXED32, schema::int32},
  {FieldDescriptor::TYPE_INT64, schema::int64},
  {FieldDescriptor::TYPE_SINT64, schema::int64},
  {FieldDescriptor::TYPE_SFIXED64, schema::int64},
  {FieldDescriptor::TYPE_UINT32, schema::uint32},
  {FieldDescriptor::TYPE_FIXED32, schema::uint32},
  {FieldDescriptor::TYPE_UINT64, schema::uint64},
  {FieldDescriptor::TYPE_FIXED64, schema::uint64},
  {FieldDescriptor::TYPE_ENUM, schema::enum_type},
  {FieldDescriptor::TYPE_MESSAGE, schema::message_type},
}
Referenced by dump_message_schema().
type_to_protobuf_type
const std::map< schema::field_type, FieldDescriptorProto_Type > automaton::core::data::protobuf::protobuf_factory::type_to_protobuf_type static
Initial value:
{
  {schema::blob, FieldDescriptorProto_Type::FieldDescriptorProto_Type_TYPE_STRING},
  {schema::boolean, FieldDescriptorProto_Type::FieldDescriptorProto_Type_TYPE_BOOL},
  {schema::int32, FieldDescriptorProto_Type::FieldDescriptorProto_Type_TYPE_INT32},
  {schema::uint32, FieldDescriptorProto_Type::FieldDescriptorProto_Type_TYPE_UINT32},
  {schema::enum_type, FieldDescriptorProto_Type::FieldDescriptorProto_Type_TYPE_ENUM},
  {schema::message_type, FieldDescriptorProto_Type::FieldDescriptorProto_Type_TYPE_MESSAGE},
}
Referenced by automaton::core::data::protobuf::protobuf_schema::add_scalar_field().
The documentation for this class was generated from the following files:
protobuf_factory.h
protobuf_factory.cc