Automaton Core: automaton::core::network::simulated_connection Class Reference
automaton::core::network::simulated_connection Class Reference
#include <simulated_connection.h>
Classes
struct incoming_packet
struct outgoing_packet
Public Member Functions
simulated_connection (connection_id id, const std::string &address_, std::shared_ptr< connection_handler > handler_)
~simulated_connection ()
void async_read (std::shared_ptr< char > buffer, uint32_t buffer_size, uint32_t num_bytes, uint32_t id)
void async_send (const std::string &message, uint32_t message_id)
void cancel_operations ()
void clear_queues ()
void connect ()
void disconnect ()
std::string get_address () const
std::shared_ptr< connection_handler > get_handler ()
uint32_t get_lag () const
state get_state () const
uint32_t get_time_stamp () const
void handle_read ()
void handle_send ()
bool init ()
bool parse_address (const std::string &address_, connection_params *params, uint32_t *parsed_remote_address)
void set_state (connection::state new_state)
void set_time_stamp (uint32_t t)
Public Member Functions inherited from automaton::core::network::connection
virtual ~connection ()
connection_id get_id ()
Public Attributes
uint32_t local_connection_id
connection_params parameters
std::queue< incoming_packet > reading
std::mutex reading_q_mutex
std::queue< std::string > receive_buffer
std::mutex recv_buf_mutex
uint32_t remote_address
uint32_t remote_connection_id
std::queue< outgoing_packet > sending
std::mutex sending_q_mutex
Additional Inherited Members
Public Types inherited from automaton::core::network::connection
typedef std::shared_ptr< connection >(* factory_function) (connection_id id, const std::string &address, std::shared_ptr< connection_handler > handler)
enum state { invalid_state = 0, connecting = 1, connected = 2, disconnected = 3 }
Static Public Member Functions inherited from automaton::core::network::connection
static std::shared_ptr< connection > create (const std::string &type, connection_id id, const std::string &address, std::shared_ptr< connection_handler > handler)
static void register_connection_type (const std::string &type, factory_function func)
Protected Member Functions inherited from automaton::core::network::connection
connection (connection_id id, std::shared_ptr< connection_handler > handler_)
Protected Attributes inherited from automaton::core::network::connection
std::shared_ptr< connection_handler > handler
connection_id id
Constructor & Destructor Documentation
simulated_connection()
automaton::core::network::simulated_connection::simulated_connection (connection_id id, const std::string & address_, std::shared_ptr< connection_handler > handler_)
~simulated_connection()
automaton::core::network::simulated_connection::~simulated_connection ()
Member Function Documentation
async_read()
void automaton::core::network::simulated_connection::async_read (std::shared_ptr< char > buffer, uint32_t buffer_size, uint32_t num_bytes, uint32_t id) virtual
Function that is used to read incoming messages. Messages could be received but not read if this function was not called. When a message is ready to be read, handler's on_message_received will be called. If an error occures, handler's on_connection_error will be called.
See also
connection_handler
Parameters
[in] buffer received message with size max(buffer_size, num_bytes) will be stored here
[in] buffer_size the size of the buffer
[in] num_bytes the number of bytes that are required to be read. If a message with greater size is received, only num_bytes will be read. If a message with smaller size is received, it will not be read until at least num_bytes are received. If num_bytes = 0 then a message will be read when it is received no matter the size (but max buffer_size)
[in] id given by the user to identify this specific read call. It will be used from the handler when on_message_received is called.
See also
connection_handler::on_message_received
This function does not create event. Actual reading will happen when the other endpoint sends a message and it arrives (send event is handled and read event is created).
Implements automaton::core::network::connection.
References automaton::core::network::simulated_connection::incoming_packet::buffer, automaton::core::network::simulated_connection::incoming_packet::buffer_size, automaton::core::network::simulated_connection::incoming_packet::expect_to_read, automaton::core::network::simulation::get_simulator(), handle_read(), automaton::core::network::simulated_connection::incoming_packet::id, reading, reading_q_mutex, receive_buffer, and recv_buf_mutex.
async_send()
void automaton::core::network::simulated_connection::async_send (const std::string & message, uint32_t id) virtual
Function that is used to send message to the remote peer. On_message_sent will(depending on the specific implementation) be invoked once the message was sent successfully
Parameters
[in] message the message to be sent
[in] id given by the user identifying this concrete message. It will be used when on_message_sent is called to inform the user about successfully sent message
See also
connection_handler::on_message_sent
Implements automaton::core::network::connection.
References automaton::core::network::simulated_connection::outgoing_packet::bytes_send, automaton::core::network::connection::disconnected, automaton::core::network::simulation::get_simulator(), get_state(), handle_send(), automaton::core::network::simulated_connection::outgoing_packet::id, automaton::core::network::simulated_connection::outgoing_packet::message, sending, and sending_q_mutex.
cancel_operations()
void automaton::core::network::simulated_connection::cancel_operations ()
References automaton::core::network::simulation::get_simulator(), automaton::core::network::connection::handler, automaton::core::network::connection::id, reading, reading_q_mutex, sending, and sending_q_mutex.
clear_queues()
void automaton::core::network::simulated_connection::clear_queues ()
Clears queues related to read operation. It is used when disconnecting. Could be removed if connections are unique and won't be reused.
References reading, reading_q_mutex, receive_buffer, recv_buf_mutex, sending, and sending_q_mutex.
connect()
void automaton::core::network::simulated_connection::connect () virtual
Asynchronous connect. If an error occures, handler's on_connection_error will be called (depends on the specific implementation). If a connection is successfully made, handler's on_connected will be called (depends on the specific implementation).
Implements automaton::core::network::connection.
References get_lag(), automaton::core::network::simulation::get_simulator(), get_time_stamp(), automaton::core::network::simulation::handle_request(), local_connection_id, remote_address, and set_time_stamp().
disconnect()
void automaton::core::network::simulated_connection::disconnect () virtual
Disconnects with the remote peer. Handler's on_disconnected is called.
Implements automaton::core::network::connection.
References get_lag(), automaton::core::network::simulation::get_simulator(), get_time_stamp(), automaton::core::network::simulation::handle_disconnect(), automaton::core::network::connection::handler, automaton::core::network::connection::id, local_connection_id, remote_connection_id, and set_time_stamp().
get_address()
std::string automaton::core::network::simulated_connection::get_address () const virtual
Returns
the connection address
Implements automaton::core::network::connection.
References local_connection_id, remote_address, and remote_connection_id.
get_handler()
std::shared_ptr< connection::connection_handler > automaton::core::network::simulated_connection::get_handler ()
References automaton::core::network::connection::handler.
get_lag()
uint32_t automaton::core::network::simulated_connection::get_lag () const
References automaton::core::network::connection_params::max_lag, automaton::core::network::connection_params::min_lag, and parameters.
Referenced by connect(), disconnect(), and handle_send().
get_state()
connection::state automaton::core::network::simulated_connection::get_state () const virtual
Returns
the connection state
Implements automaton::core::network::connection.
Referenced by async_send(), handle_read(), and handle_send().
get_time_stamp()
uint32_t automaton::core::network::simulated_connection::get_time_stamp () const
Referenced by connect(), disconnect(), and handle_send().
handle_read()
void automaton::core::network::simulated_connection::handle_read ()
References automaton::core::network::simulated_connection::incoming_packet::buffer, automaton::core::network::simulated_connection::incoming_packet::buffer_size, automaton::core::network::simulated_connection::incoming_packet::bytes_read, automaton::core::network::simulated_connection::incoming_packet::expect_to_read, automaton::core::network::simulation::get_simulator(), get_state(), automaton::core::network::simulated_connection::incoming_packet::id, reading, reading_q_mutex, receive_buffer, recv_buf_mutex, and automaton::core::interop::ethereum::string.
Referenced by async_read(), and automaton::core::network::simulation::handle_message().
handle_send()
void automaton::core::network::simulated_connection::handle_send ()
nothing to send or waiting for ACK
References automaton::core::network::connection_params::bandwidth, automaton::core::network::simulated_connection::outgoing_packet::bytes_send, get_lag(), automaton::core::network::simulation::get_simulator(), get_state(), get_time_stamp(), automaton::core::network::simulation::handle_message(), local_connection_id, automaton::core::network::simulated_connection::outgoing_packet::message, parameters, remote_connection_id, sending, sending_q_mutex, set_time_stamp(), and automaton::core::interop::ethereum::string.
Referenced by async_send(), and automaton::core::network::simulation::handle_message().
init()
bool automaton::core::network::simulated_connection::init () virtual
Initialises the connection.
Returns
true if no errors occured and initialisation was successful, false, otherwise
Implements automaton::core::network::connection.
References parameters, parse_address(), and remote_address.
parse_address()
bool automaton::core::network::simulated_connection::parse_address (const std::string & address_, connection_params * params, uint32_t * parsed_remote_address)
References automaton::core::network::connection_params::bandwidth, automaton::core::network::connection_params::max_lag, and automaton::core::network::connection_params::min_lag.
Referenced by init().
set_state()
void automaton::core::network::simulated_connection::set_state (connection::state new_state)
set_time_stamp()
void automaton::core::network::simulated_connection::set_time_stamp (uint32_t t)
Referenced by connect(), disconnect(), and handle_send().
Member Data Documentation
local_connection_id
uint32_t automaton::core::network::simulated_connection::local_connection_id
Referenced by connect(), disconnect(), get_address(), and handle_send().
parameters
connection_params automaton::core::network::simulated_connection::parameters
Referenced by get_lag(), handle_send(), and init().
reading
std::queue<incoming_packet> automaton::core::network::simulated_connection::reading
Referenced by async_read(), cancel_operations(), clear_queues(), and handle_read().
reading_q_mutex
std::mutex automaton::core::network::simulated_connection::reading_q_mutex
Referenced by async_read(), cancel_operations(), clear_queues(), and handle_read().
receive_buffer
std::queue<std::string> automaton::core::network::simulated_connection::receive_buffer
Referenced by async_read(), clear_queues(), and handle_read().
recv_buf_mutex
std::mutex automaton::core::network::simulated_connection::recv_buf_mutex
Referenced by async_read(), clear_queues(), and handle_read().
remote_address
uint32_t automaton::core::network::simulated_connection::remote_address
Referenced by connect(), get_address(), and init().
remote_connection_id
uint32_t automaton::core::network::simulated_connection::remote_connection_id
Referenced by disconnect(), get_address(), and handle_send().
sending
std::queue<outgoing_packet> automaton::core::network::simulated_connection::sending
Referenced by async_send(), cancel_operations(), clear_queues(), and handle_send().
sending_q_mutex
std::mutex automaton::core::network::simulated_connection::sending_q_mutex
Referenced by async_send(), cancel_operations(), clear_queues(), and handle_send().
The documentation for this class was generated from the following files:
simulated_connection.h
simulated_connection.cc