Automaton Core: automaton::core::data::protobuf::protobuf_msg Class Reference
automaton::core::data::protobuf::protobuf_msg Class Reference
#include <protobuf_msg.h>
Public Member Functions
protobuf_msg (google::protobuf::Message *m, factory *msg_factory, uint32_t schema_id)
bool deserialize_message (const std::string &input)
bool from_json (const std::string &input)
std::string get_blob (uint32_t field_tag) const
bool get_boolean (uint32_t field_tag) const
int32_t get_enum (uint32_t field_tag) const
factory * get_factory () const
schema::field_info get_field_info_by_tag (uint32_t field_tag) const
uint32_t get_field_tag (const std::string &name) const
int32_t get_int32 (uint32_t field_tag) const
int64_t get_int64 (uint32_t field_tag) const
std::unique_ptr< msg > get_message (uint32_t field_tag) const
std::string get_message_type () const
std::string get_repeated_blob (uint32_t field_tag, int32_t index) const
bool get_repeated_boolean (uint32_t field_tag, int32_t index) const
int32_t get_repeated_enum (uint32_t field_tag, int32_t index) const
uint32_t get_repeated_field_size (uint32_t field_tag) const
int32_t get_repeated_int32 (uint32_t field_tag, int32_t index) const
int64_t get_repeated_int64 (uint32_t field_tag, int32_t index) const
std::unique_ptr< msg > get_repeated_message (uint32_t field_tag, int32_t index) const
uint32_t get_repeated_uint32 (uint32_t field_tag, int32_t index) const
uint64_t get_repeated_uint64 (uint32_t field_tag, int32_t index) const
uint32_t get_schema_id () const
uint32_t get_uint32 (uint32_t field_tag) const
uint64_t get_uint64 (uint32_t field_tag) const
bool serialize_message (std::string *output) const
void set_blob (uint32_t field_tag, const std::string &value)
Blob (string, bytes, ...)
void set_boolean (uint32_t field_tag, bool value)
Boolean.
void set_enum (uint32_t field_tag, int32_t value)
void set_int32 (uint32_t field_tag, int32_t value)
Int 32.
void set_int64 (uint32_t field_tag, int64_t value)
Int 64.
void set_message (uint32_t field_tag, const msg &sub_message)
Message.
void set_repeated_blob (uint32_t field_tag, const std::string &value, int32_t index)
void set_repeated_boolean (uint32_t field_tag, bool value, int32_t index)
void set_repeated_enum (uint32_t field_tag, int32_t value, int32_t index)
void set_repeated_int32 (uint32_t field_tag, int32_t value, int32_t index)
void set_repeated_int64 (uint32_t field_tag, int64_t value, int32_t index)
void set_repeated_message (uint32_t field_tag, const msg &sub_message, int32_t index)
void set_repeated_uint32 (uint32_t field_tag, uint32_t value, int32_t index)
void set_repeated_uint64 (uint32_t field_tag, uint64_t value, int32_t index)
void set_uint32 (uint32_t field_tag, uint32_t value)
uint32_t 32
void set_uint64 (uint32_t field_tag, uint64_t value)
uint32_t 64
bool to_json (std::string *output) const
std::string to_string () const
Public Member Functions inherited from automaton::core::data::msg
msg ()
msg (const msg &that)=delete
virtual ~msg ()=0
Detailed Description
Google Protobuf msg implementation.
This is a wrapper around google::protobuf::Message.
Constructor & Destructor Documentation
protobuf_msg()
automaton::core::data::protobuf::protobuf_msg::protobuf_msg (google::protobuf::Message * m, factory * msg_factory, uint32_t schema_id)
Constructs a protobuf msg implementation.
Referenced by get_message(), and get_repeated_message().
Member Function Documentation
deserialize_message()
bool automaton::core::data::protobuf::protobuf_msg::deserialize_message (const std::string & input) virtual
Deserializes message from the given string into a message with the given message id. If no such message exists or some error while deserializing happens, exception will be thrown. To use this function you should first create new message from the same schema and pass the id to this function.
Implements automaton::core::data::msg.
References CHECK_NOTNULL.
from_json()
bool automaton::core::data::protobuf::protobuf_msg::from_json (const std::string & input) virtual
Deserializes message from JSON string.
Implements automaton::core::data::msg.
References CHECK_NOTNULL.
get_blob()
string automaton::core::data::protobuf::protobuf_msg::get_blob (uint32_t field_tag) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_boolean()
bool automaton::core::data::protobuf::protobuf_msg::get_boolean (uint32_t field_tag) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_enum()
int32_t automaton::core::data::protobuf::protobuf_msg::get_enum (uint32_t field_tag) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_factory()
factory * automaton::core::data::protobuf::protobuf_msg::get_factory () const
get_field_info_by_tag()
schema::field_info automaton::core::data::protobuf::protobuf_msg::get_field_info_by_tag (uint32_t field_tag) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::schema::enum_type, automaton::core::data::schema::message_type, and automaton::core::data::protobuf::protobuf_factory::protobuf_ccptype_to_type.
get_field_tag()
uint32_t automaton::core::data::protobuf::protobuf_msg::get_field_tag (const std::string & name) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_int32()
int32_t automaton::core::data::protobuf::protobuf_msg::get_int32 (uint32_t field_tag) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_int64()
int64_t automaton::core::data::protobuf::protobuf_msg::get_int64 (uint32_t field_tag) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_message()
std::unique_ptr< msg > automaton::core::data::protobuf::protobuf_msg::get_message (uint32_t field_tag) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::factory::get_schema_id(), automaton::core::data::msg::msg(), protobuf_msg(), and el::base::debug::StackTrace().
get_message_type()
string automaton::core::data::protobuf::protobuf_msg::get_message_type () const virtual
Returns the name of the message schema.
If schema with the given name doesn't exist, exception will be thrown.
Implements automaton::core::data::msg.
get_repeated_blob()
string automaton::core::data::protobuf::protobuf_msg::get_repeated_blob (uint32_t field_tag, int32_t index) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_repeated_boolean()
bool automaton::core::data::protobuf::protobuf_msg::get_repeated_boolean (uint32_t field_tag, int32_t index) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_repeated_enum()
int32_t automaton::core::data::protobuf::protobuf_msg::get_repeated_enum (uint32_t field_tag, int32_t index) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_repeated_field_size()
uint32_t automaton::core::data::protobuf::protobuf_msg::get_repeated_field_size (uint32_t field_tag) const virtual
Returns the size of the repeated field in the given message. If no such message or field exists or if the field is not repeated, exception will be thrown.
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_repeated_int32()
int32_t automaton::core::data::protobuf::protobuf_msg::get_repeated_int32 (uint32_t field_tag, int32_t index) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_repeated_int64()
int64_t automaton::core::data::protobuf::protobuf_msg::get_repeated_int64 (uint32_t field_tag, int32_t index) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_repeated_message()
std::unique_ptr< msg > automaton::core::data::protobuf::protobuf_msg::get_repeated_message (uint32_t field_tag, int32_t index) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::factory::get_schema_id(), automaton::core::data::msg::msg(), protobuf_msg(), and el::base::debug::StackTrace().
get_repeated_uint32()
uint32_t automaton::core::data::protobuf::protobuf_msg::get_repeated_uint32 (uint32_t field_tag, int32_t index) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_repeated_uint64()
uint64_t automaton::core::data::protobuf::protobuf_msg::get_repeated_uint64 (uint32_t field_tag, int32_t index) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_schema_id()
uint32_t automaton::core::data::protobuf::protobuf_msg::get_schema_id () const virtual
Implements automaton::core::data::msg.
get_uint32()
uint32_t automaton::core::data::protobuf::protobuf_msg::get_uint32 (uint32_t field_tag) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
get_uint64()
uint64_t automaton::core::data::protobuf::protobuf_msg::get_uint64 (uint32_t field_tag) const virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
serialize_message()
bool automaton::core::data::protobuf::protobuf_msg::serialize_message (std::string * output) const virtual
Serializes the given message into the given string. If no such message exists or some error while serializing happens, exception will be thrown.
Implements automaton::core::data::msg.
References CHECK_NOTNULL.
set_blob()
void automaton::core::data::protobuf::protobuf_msg::set_blob (uint32_t field_tag, const std::string & value) virtual
Blob (string, bytes, ...)
Setters and getters for the scalar types. If any tag or id is invalid, or if you try to use these functions on non-matching type fields, or if you try to use get/set_repeated_*() on non-repeated field or vise versa, exception will be thrown. If you use out of range index on set_repeated_*() the value will just be added at the end (not on the specified index). If you use out of range index on set_repeated_*(), exception will be thrown.
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_boolean()
void automaton::core::data::protobuf::protobuf_msg::set_boolean (uint32_t field_tag, bool value) virtual
Boolean.
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_enum()
void automaton::core::data::protobuf::protobuf_msg::set_enum (uint32_t field_tag, int32_t value) virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_int32()
void automaton::core::data::protobuf::protobuf_msg::set_int32 (uint32_t field_tag, int32_t value) virtual
Int 32.
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_int64()
void automaton::core::data::protobuf::protobuf_msg::set_int64 (uint32_t field_tag, int64_t value) virtual
Int 64.
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_message()
void automaton::core::data::protobuf::protobuf_msg::set_message (uint32_t field_tag, const msg & sub_message) virtual
Message.
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_repeated_blob()
void automaton::core::data::protobuf::protobuf_msg::set_repeated_blob (uint32_t field_tag, const std::string & value, int32_t index) virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_repeated_boolean()
void automaton::core::data::protobuf::protobuf_msg::set_repeated_boolean (uint32_t field_tag, bool value, int32_t index) virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_repeated_enum()
void automaton::core::data::protobuf::protobuf_msg::set_repeated_enum (uint32_t field_tag, int32_t value, int32_t index) virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_repeated_int32()
void automaton::core::data::protobuf::protobuf_msg::set_repeated_int32 (uint32_t field_tag, int32_t value, int32_t index) virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_repeated_int64()
void automaton::core::data::protobuf::protobuf_msg::set_repeated_int64 (uint32_t field_tag, int64_t value, int32_t index) virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_repeated_message()
void automaton::core::data::protobuf::protobuf_msg::set_repeated_message (uint32_t field_tag, const msg & sub_message, int32_t index) virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_repeated_uint32()
void automaton::core::data::protobuf::protobuf_msg::set_repeated_uint32 (uint32_t field_tag, uint32_t value, int32_t index) virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_repeated_uint64()
void automaton::core::data::protobuf::protobuf_msg::set_repeated_uint64 (uint32_t field_tag, uint64_t value, int32_t index) virtual
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_uint32()
void automaton::core::data::protobuf::protobuf_msg::set_uint32 (uint32_t field_tag, uint32_t value) virtual
uint32_t 32
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
set_uint64()
void automaton::core::data::protobuf::protobuf_msg::set_uint64 (uint32_t field_tag, uint64_t value) virtual
uint32_t 64
Implements automaton::core::data::msg.
References CHECK_NOTNULL, automaton::core::data::msg::msg(), and el::base::debug::StackTrace().
to_json()
bool automaton::core::data::protobuf::protobuf_msg::to_json (std::string * output) const virtual
Serializes message to JSON string.
Implements automaton::core::data::msg.
References CHECK_NOTNULL.
to_string()
string automaton::core::data::protobuf::protobuf_msg::to_string () const virtual
Returns human readable representation of the message with the given id. If message id is not valid, exception will be thrown.
Implements automaton::core::data::msg.
References CHECK_NOTNULL.
The documentation for this class was generated from the following files:
protobuf_msg.h
protobuf_msg.cc