Automaton Core: automaton::core::network::tcp_acceptor Class Reference
automaton::core::network::tcp_acceptor Class Reference
#include <tcp_implementation.h>
Public Member Functions
tcp_acceptor (acceptor_id id, const std::string &address, std::shared_ptr< acceptor_handler > handler_, std::shared_ptr< connection::connection_handler > connections_handler)
~tcp_acceptor ()
std::string get_address () const
acceptor::state get_state () const
bool init ()
Initialises the acceptor.
void start_accepting ()
The acceptor starts to listen for incoming connections. Asynchronous.
void stop_accepting ()
Public Member Functions inherited from automaton::core::network::acceptor
virtual ~acceptor ()
acceptor_id get_id ()
Additional Inherited Members
Public Types inherited from automaton::core::network::acceptor
typedef std::shared_ptr< acceptor >(* factory_function) (acceptor_id id, const std::string &address, std::shared_ptr< acceptor_handler > handler_, std::shared_ptr< connection::connection_handler > connections_handler)
enum state { invalid_state = 0, accepting = 1, not_accepting = 2 }
Static Public Member Functions inherited from automaton::core::network::acceptor
static std::shared_ptr< acceptor > create (const std::string &type, acceptor_id id, const std::string &address, std::shared_ptr< acceptor_handler > handler_, std::shared_ptr< connection::connection_handler > connections_handler)
static void register_acceptor_type (const std::string &type, factory_function func)
Protected Member Functions inherited from automaton::core::network::acceptor
acceptor (acceptor_id id, std::shared_ptr< acceptor_handler > handler_)
Protected Attributes inherited from automaton::core::network::acceptor
std::shared_ptr< acceptor_handler > handler
acceptor_id id
Constructor & Destructor Documentation
tcp_acceptor()
automaton::core::network::tcp_acceptor::tcp_acceptor (acceptor_id id, const std::string & address, std::shared_ptr< acceptor_handler > handler_, std::shared_ptr< connection::connection_handler > connections_handler)
See also
acceptor::create
acceptor::factory_function
References automaton::core::network::asio_io_service.
~tcp_acceptor()
automaton::core::network::tcp_acceptor::~tcp_acceptor ()
Destructor.
Member Function Documentation
get_address()
std::string automaton::core::network::tcp_acceptor::get_address () const virtual
Returns
the acceptor's address
Implements automaton::core::network::acceptor.
get_state()
acceptor::state automaton::core::network::tcp_acceptor::get_state () const virtual
Returns
the acceptor's state
Implements automaton::core::network::acceptor.
init()
bool automaton::core::network::tcp_acceptor::init () virtual
Initialises the acceptor.
Precondition
tcp_init() to has been called, error will happen, otherwise
Parses the address and tries to open an acceptor and bind it to the specified address. If port 0 is given in the address, random port will be assigned and the address of the acceptor will be updated to include the new port. If the initialisation is successful, the acceptor will start to listen for new connections, but none will be accepted until start_accepting is called.
Returns
true if the initialisation is successful, false if an error occures. If there was an error while initialisation, it will be logged.
Implements automaton::core::network::acceptor.
References automaton::core::network::asio_io_service, automaton::core::network::parse_address(), automaton::core::interop::ethereum::string, and automaton::core::network::tcp_initialized.
start_accepting()
void automaton::core::network::tcp_acceptor::start_accepting () virtual
The acceptor starts to listen for incoming connections. Asynchronous.
This function is called from the constructor to start asynchronous accepting. When a remote peer request to make a connection, handler's on_requested() method will be called, passing peer's address and waiting for confirmaton to accept or not. If on_requested() returns true, then a connection is created and its handler's on_connected() called. Acceptor's handler's on_connected will also be called and a pointer to the created connection passed. If an error occured while accepting, handler's on_acceptor_error() will be called.
Precondition
tcp_initialized == true meaning tcp_init() to be called
socket to be open. Socket opens on connection construction or when connect() is called and didn't fail. If disconnect() has been called, connect() should be called before this function.
If any of the preconditions is not met on_acceptor_error() will be called with status::internal, containing an error.
See also
common::status
Implements automaton::core::network::acceptor.
References automaton::core::network::asio_io_service, automaton::core::network::acceptor::handler, automaton::core::network::acceptor::acceptor_handler::on_acceptor_error(), automaton::core::network::acceptor::acceptor_handler::on_connected(), automaton::core::network::acceptor::acceptor_handler::on_requested(), automaton::core::interop::ethereum::string, and automaton::core::network::tcp_initialized.
stop_accepting()
void automaton::core::network::tcp_acceptor::stop_accepting () virtual
The acceptor stops to listen for incoming connections.
Implements automaton::core::network::acceptor.
The documentation for this class was generated from the following files:
tcp_implementation.h
tcp_implementation.cc