Automaton Core: automaton::core::data::protobuf::protobuf_schema Class Reference
automaton::core::data::protobuf::protobuf_schema Class Reference
#include <protobuf_schema.h>
Public Member Functions
protobuf_schema ()
protobuf_schema (const std::string &proto_def)
~protobuf_schema ()
void add_dependency (const std::string &schema_name)
void add_enum (uint32_t enum_id, int32_t message_id)
void add_enum_field (schema::field_info field, int32_t message_id)
void add_enum_value (uint32_t enum_id, const std::string &value_name, int32_t value)
void add_message (int32_t message_id)
void add_message_field (schema::field_info field, int32_t message_id)
void add_nested_message (int32_t message_id, uint32_t sub_message_id)
void add_scalar_field (schema::field_info field, int32_t message_id)
uint32_t create_enum (const std::string &enum_name)
uint32_t create_message (const std::string &message_name)
std::string dump_schema ()
bool from_json (const std::string &input)
google::protobuf::FileDescriptorProto * get_file_descriptor_proto ()
std::vector< std::string > get_message_names ()
bool to_json (std::string *output) const
Public Member Functions inherited from automaton::core::data::schema
virtual ~schema ()=0
Additional Inherited Members
Public Types inherited from automaton::core::data::schema
enum field_type {
unknown = 0, message_type = 1, enum_type = 2, blob = 4,
int32 = 5, int64 = 6, uint32 = 7, uint64 = 8,
boolean = 9
}
Constructor & Destructor Documentation
protobuf_schema() [1/2]
automaton::core::data::protobuf::protobuf_schema::protobuf_schema ()
protobuf_schema() [2/2]
automaton::core::data::protobuf::protobuf_schema::protobuf_schema (const std::string & proto_def) explicit
References automaton::core::data::protobuf::io_error_collector::get_all_errors(), automaton::core::data::protobuf::io_error_collector::get_number_errors(), and el::base::debug::StackTrace().
~protobuf_schema()
automaton::core::data::protobuf::protobuf_schema::~protobuf_schema ()
Member Function Documentation
add_dependency()
void automaton::core::data::protobuf::protobuf_schema::add_dependency (const std::string & schema_name) virtual
If this schema (schema A) depends on another one (schema B), it must be added here. Schema_name is the name that has been/will be given to the schema (B) on import (when schema::import_schema_definition() is called). Shema B should be imported before Schema A.
Implements automaton::core::data::schema.
add_enum()
void automaton::core::data::protobuf::protobuf_schema::add_enum (uint32_t enum_id, int32_t message_id) virtual
Implements automaton::core::data::schema.
References el::base::debug::StackTrace().
add_enum_field()
void automaton::core::data::protobuf::protobuf_schema::add_enum_field (schema::field_info field, int32_t message_id) virtual
Implements automaton::core::data::schema.
References CHECK_BOUNDS, automaton::core::data::schema::enum_type, automaton::core::data::schema::field_info::fully_qualified_type, automaton::core::data::schema::field_info::is_repeated, automaton::core::data::schema::field_info::name, el::base::debug::StackTrace(), automaton::core::data::schema::field_info::tag, and automaton::core::data::schema::field_info::type.
add_enum_value()
void automaton::core::data::protobuf::protobuf_schema::add_enum_value (uint32_t enum_id, const std::string & value_name, int32_t value) virtual
Used to add values to an already created enum with enum_id. If such enum doesn't exist, exception will be thrown. TODO(kari): Decide if duplicate values are allowed.
Implements automaton::core::data::schema.
References el::base::debug::StackTrace().
add_message()
void automaton::core::data::protobuf::protobuf_schema::add_message (int32_t message_id) virtual
Used to add an already created message/enum schema to this schema. The message/enum should first be created and ready (fields/ nested messages/ enums or enum values must be added) before calling this function. Enum can be added to another message and if no message_id is provided in add_enum or message_id = -1, enum will be added globally. If message/enum with the given id doesn't exist, exception will be thrown.
Implements automaton::core::data::schema.
References CHECK_BOUNDS, and el::base::debug::StackTrace().
add_message_field()
void automaton::core::data::protobuf::protobuf_schema::add_message_field (schema::field_info field, int32_t message_id) virtual
Implements automaton::core::data::schema.
References CHECK_BOUNDS, automaton::core::data::schema::field_info::fully_qualified_type, automaton::core::data::schema::field_info::is_repeated, automaton::core::data::schema::message_type, automaton::core::data::schema::field_info::name, el::base::debug::StackTrace(), automaton::core::data::schema::field_info::tag, and automaton::core::data::schema::field_info::type.
add_nested_message()
void automaton::core::data::protobuf::protobuf_schema::add_nested_message (int32_t message_id, uint32_t sub_message_id) virtual
Used to add nested message. Both messages must already exist. If any of them doesn't exist, exception will be thrown. The message with id sub_message_id will be added as a nested message to the other. Nested message is different from message field. It is like an inner class, NOT like a reference to an object *** TODO(kari): Decide if duplicate values are allowed.
Implements automaton::core::data::schema.
References CHECK_BOUNDS, CHECK_LT, and el::base::debug::StackTrace().
add_scalar_field()
void automaton::core::data::protobuf::protobuf_schema::add_scalar_field (schema::field_info field, int32_t message_id) virtual
These functions are called to add fields to a message. Any of them can be called multiple times on the same message. If the given message_id is not valid or the given field doesn't match the expected field type (ex. add_message_field() is called but the provided field is scalar type), exception will be thrown.
Implements automaton::core::data::schema.
References CHECK_BOUNDS, automaton::core::data::schema::enum_type, automaton::core::data::schema::field_info::is_repeated, automaton::core::data::schema::message_type, automaton::core::data::schema::field_info::name, el::base::debug::StackTrace(), automaton::core::data::schema::field_info::tag, automaton::core::data::schema::field_info::type, automaton::core::data::protobuf::protobuf_factory::type_to_protobuf_type, and automaton::core::data::schema::unknown.
create_enum()
uint32_t automaton::core::data::protobuf::protobuf_schema::create_enum (const std::string & enum_name) virtual
Returns the id of the created enum_schema. Only creates empty enum schema and name it. Values should be added to the enum (using add_enum_value) and then add_enum() so the created enum schema is added to the schema.
Implements automaton::core::data::schema.
create_message()
uint32_t automaton::core::data::protobuf::protobuf_schema::create_message (const std::string & message_name) virtual
Returns the id of the created message_schema. Only creates empty message schema and name it. Fields and/or nested enums/messages should be added to the message (using add_* and add_*_field) and then add_message() so the created message schema is added to the schema.
Implements automaton::core::data::schema.
dump_schema()
std::string automaton::core::data::protobuf::protobuf_schema::dump_schema () virtual
Implements automaton::core::data::schema.
References automaton::core::data::protobuf::dump_msg().
from_json()
bool automaton::core::data::protobuf::protobuf_schema::from_json (const std::string & input) virtual
Deserializes schema from JSON string.
Implements automaton::core::data::schema.
References CHECK_NOTNULL.
get_file_descriptor_proto()
FileDescriptorProto * automaton::core::data::protobuf::protobuf_schema::get_file_descriptor_proto ()
This function is used from protobuf_factory on import. (Instead of friend class)
get_message_names()
std::vector< std::string > automaton::core::data::protobuf::protobuf_schema::get_message_names () virtual
Implements automaton::core::data::schema.
to_json()
bool automaton::core::data::protobuf::protobuf_schema::to_json (std::string * output) const virtual
Serializes schema to JSON string.
Implements automaton::core::data::schema.
References CHECK_NOTNULL.
The documentation for this class was generated from the following files:
protobuf_schema.h
protobuf_schema.cc