Automaton Core: automaton::core::crypto::hash_transformation Class Reference
automaton::core::crypto::hash_transformation Class Reference abstract
#include <hash_transformation.h>
Public Member Functions
virtual ~hash_transformation ()
virtual void calculate_digest (const uint8_t *input, const size_t length, uint8_t *digest)
virtual uint32_t digest_size () const =0
virtual void final (uint8_t *digest)=0
virtual void restart ()=0
virtual void update (const uint8_t *input, const size_t length)=0
Constructor & Destructor Documentation
~hash_transformation()
virtual automaton::core::crypto::hash_transformation::~hash_transformation () inline virtual
Member Function Documentation
calculate_digest()
void automaton::core::crypto::hash_transformation::calculate_digest (const uint8_t * input, const size_t length, uint8_t * digest) virtual
Reimplemented in automaton::core::crypto::cryptopp::SHA512_cryptopp, automaton::core::crypto::cryptopp::SHA3_256_cryptopp, automaton::core::crypto::cryptopp::SHA256_cryptopp, automaton::core::crypto::cryptopp::RIPEMD160_cryptopp, and automaton::core::crypto::cryptopp::Keccak_256_cryptopp.
References update().
digest_size()
virtual uint32_t automaton::core::crypto::hash_transformation::digest_size () const pure virtual
Implemented in automaton::core::crypto::cryptopp::SHA512_cryptopp, automaton::core::crypto::cryptopp::SHA3_256_cryptopp, automaton::core::crypto::cryptopp::SHA256_cryptopp, automaton::core::crypto::cryptopp::RIPEMD160_cryptopp, and automaton::core::crypto::cryptopp::Keccak_256_cryptopp.
Referenced by automaton::core::state::state_impl::hash_size(), and automaton::core::state::state_persistent::hash_size().
final()
virtual void automaton::core::crypto::hash_transformation::final (uint8_t * digest) pure virtual
Implemented in automaton::core::crypto::cryptopp::SHA512_cryptopp, automaton::core::crypto::cryptopp::SHA3_256_cryptopp, automaton::core::crypto::cryptopp::SHA256_cryptopp, automaton::core::crypto::cryptopp::RIPEMD160_cryptopp, and automaton::core::crypto::cryptopp::Keccak_256_cryptopp.
restart()
virtual void automaton::core::crypto::hash_transformation::restart () pure virtual
Implemented in automaton::core::crypto::cryptopp::SHA512_cryptopp, automaton::core::crypto::cryptopp::SHA3_256_cryptopp, automaton::core::crypto::cryptopp::SHA256_cryptopp, automaton::core::crypto::cryptopp::RIPEMD160_cryptopp, and automaton::core::crypto::cryptopp::Keccak_256_cryptopp.
update()
virtual void automaton::core::crypto::hash_transformation::update (const uint8_t * input, const size_t length) pure virtual
Implemented in automaton::core::crypto::cryptopp::SHA512_cryptopp, automaton::core::crypto::cryptopp::SHA3_256_cryptopp, automaton::core::crypto::cryptopp::SHA256_cryptopp, automaton::core::crypto::cryptopp::RIPEMD160_cryptopp, and automaton::core::crypto::cryptopp::Keccak_256_cryptopp.
Referenced by calculate_digest().
The documentation for this class was generated from the following files:
hash_transformation.h
hash_transformation.cc