Automaton Core: automaton::core::smartproto::smart_protocol Class Reference
automaton::core::smartproto::smart_protocol Class Reference
#include <smart_protocol.h>
Classes
struct cmd
Public Member Functions
~smart_protocol ()
std::vector< std::string > get_commands ()
std::string get_configuration_file ()
std::shared_ptr< data::factory > get_factory ()
int32_t get_factory_from_wire (int32_t)
std::unordered_map< std::string, std::string > get_files (std::string files_type)
std::unordered_map< std::string, std::string > get_msgs_definitions ()
std::vector< data::schema * > get_schemas ()
uint32_t get_update_time_slice ()
int32_t get_wire_from_factory (int32_t)
std::vector< std::string > get_wire_msgs ()
Static Public Member Functions
static std::shared_ptr< smart_protocol > get_protocol (const std::string &proto_id)
static std::vector< std::string > list_protocols ()
static bool load (const std::string &id, const std::string &path)
Constructor & Destructor Documentation
~smart_protocol()
automaton::core::smartproto::smart_protocol::~smart_protocol ()
Member Function Documentation
get_commands()
std::vector< std::string > automaton::core::smartproto::smart_protocol::get_commands ()
Referenced by automaton::core::node::luanode::lua_node::init().
get_configuration_file()
std::string automaton::core::smartproto::smart_protocol::get_configuration_file ()
get_factory()
std::shared_ptr< data::factory > automaton::core::smartproto::smart_protocol::get_factory ()
Referenced by automaton::core::node::luanode::lua_node::init().
get_factory_from_wire()
int32_t automaton::core::smartproto::smart_protocol::get_factory_from_wire (int32_t wire_id)
get_files()
std::unordered_map< std::string, std::string > automaton::core::smartproto::smart_protocol::get_files (std::string files_type)
Referenced by automaton::core::node::luanode::lua_node::init().
get_msgs_definitions()
std::unordered_map< std::string, std::string > automaton::core::smartproto::smart_protocol::get_msgs_definitions ()
get_protocol()
std::shared_ptr< smart_protocol > automaton::core::smartproto::smart_protocol::get_protocol (const std::string & proto_id) static
Referenced by automaton::core::node::luanode::lua_node::init(), and automaton::core::node::node::node().
get_schemas()
std::vector< data::schema * > automaton::core::smartproto::smart_protocol::get_schemas ()
Referenced by automaton::core::node::luanode::lua_node::init().
get_update_time_slice()
uint32_t automaton::core::smartproto::smart_protocol::get_update_time_slice ()
get_wire_from_factory()
int32_t automaton::core::smartproto::smart_protocol::get_wire_from_factory (int32_t msg_schema_id)
get_wire_msgs()
std::vector< std::string > automaton::core::smartproto::smart_protocol::get_wire_msgs ()
Referenced by automaton::core::node::luanode::lua_node::init().
list_protocols()
std::vector< std::string > automaton::core::smartproto::smart_protocol::list_protocols () static
load()
bool automaton::core::smartproto::smart_protocol::load (const std::string & id, const std::string & path) static
References automaton::core::io::get_file_contents(), and automaton::core::interop::ethereum::string.
The documentation for this class was generated from the following files:
smart_protocol.h
smart_protocol.cc