Automaton Core: automaton::core::state::state_persistent Class Reference
automaton::core::state::state_persistent Class Reference
#include <state_persistent.h>
Classes
class node
Public Member Functions
state_persistent (crypto::hash_transformation *hasher, storage::blobstore *bs, storage::persistent_vector< node > *p_nodes)
void commit_changes ()
void delete_node_tree (const std::string &path)
void discard_changes ()
void erase (const std::string &path)
std::string get (const std::string &key)
std::vector< std::string > get_node_children (const std::string &path)
std::string get_node_hash (const std::string &path)
uint32_t hash_size ()
void print_subtrie (std::string path, std::string formated_path)
void set (const std::string &key, const std::string &value)
uint32_t size ()
Public Member Functions inherited from automaton::core::state::state
virtual ~state ()
Constructor & Destructor Documentation
state_persistent()
automaton::core::state::state_persistent::state_persistent (crypto::hash_transformation * hasher, storage::blobstore * bs, storage::persistent_vector< node > * p_nodes)
References nodes, and automaton::core::storage::blobstore::store().
Member Function Documentation
commit_changes()
void automaton::core::state::state_persistent::commit_changes () virtual
Implements automaton::core::state::state.
References nodes.
delete_node_tree()
void automaton::core::state::state_persistent::delete_node_tree (const std::string & path) virtual
Implements automaton::core::state::state.
References automaton::core::io::bin2hex(), nodes, and automaton::core::interop::ethereum::string.
discard_changes()
void automaton::core::state::state_persistent::discard_changes () virtual
Implements automaton::core::state::state.
References nodes.
erase()
void automaton::core::state::state_persistent::erase (const std::string & path) virtual
Implements automaton::core::state::state.
References automaton::core::io::bin2hex(), nodes, and automaton::core::interop::ethereum::string.
get()
std::string automaton::core::state::state_persistent::get (const std::string & key) virtual
Implements automaton::core::state::state.
References nodes.
Referenced by print_subtrie().
get_node_children()
std::vector< std::string > automaton::core::state::state_persistent::get_node_children (const std::string & path) virtual
Implements automaton::core::state::state.
References nodes, and automaton::core::interop::ethereum::string.
Referenced by print_subtrie().
get_node_hash()
std::string automaton::core::state::state_persistent::get_node_hash (const std::string & path) virtual
Implements automaton::core::state::state.
References nodes.
Referenced by print_subtrie().
hash_size()
uint32_t automaton::core::state::state_persistent::hash_size () virtual
Implements automaton::core::state::state.
References automaton::core::crypto::hash_transformation::digest_size().
print_subtrie()
void automaton::core::state::state_persistent::print_subtrie (std::string path, std::string formated_path)
References automaton::core::io::bin2hex(), get(), get_node_children(), get_node_hash(), and nodes.
set()
void automaton::core::state::state_persistent::set (const std::string & key, const std::string & value) virtual
Implements automaton::core::state::state.
References nodes, and automaton::core::interop::ethereum::string.
size()
uint32_t automaton::core::state::state_persistent::size ()
References nodes.
The documentation for this class was generated from the following files:
state_persistent.h
state_persistent.cc