Automaton Core: automaton::core::script::registry Class Reference
automaton::core::script::registry Class Reference
#include <registry.h>
Public Member Functions
registry (const registry &)=delete
registry (registry &)=delete
std::unique_ptr< common::obj > create (const data::msg &m)
data::factory & get_factory ()
module * get_module (std::string name)
template<typename M >
void import ()
std::vector< std::string > module_names ()
void process (const data::msg &request, data::msg *response)
std::string to_string ()
Static Public Member Functions
static registry & instance ()
Detailed Description
Registry for scriptable modules.
Constructor & Destructor Documentation
registry() [1/2]
automaton::core::script::registry::registry (registry &) delete
registry() [2/2]
automaton::core::script::registry::registry (const registry &) delete
Member Function Documentation
create()
std::unique_ptr< common::obj > automaton::core::script::registry::create (const data::msg & m)
References automaton::core::data::msg::get_message_type().
get_factory()
data::factory& automaton::core::script::registry::get_factory () inline
Referenced by automaton::core::script::module::add_implementation(), automaton::core::script::module::bind_schemas(), and automaton::core::script::module::check_implementation().
get_module()
module* automaton::core::script::registry::get_module (std::string name) inline
import()
template<typename M > void automaton::core::script::registry::import () inline
Binds module M to the script::registry.
References el::base::debug::StackTrace(), and automaton::core::interop::ethereum::string.
instance()
static registry& automaton::core::script::registry::instance () inline static
Gets reference to the registry instance.
Creates the instance when called for the first time.
Referenced by automaton::core::script::module::add_implementation(), automaton::core::script::module::bind_schemas(), and automaton::core::script::module::check_implementation().
module_names()
std::vector<std::string> automaton::core::script::registry::module_names () inline
process()
void automaton::core::script::registry::process (const data::msg & request, data::msg * response)
to_string()
std::string automaton::core::script::registry::to_string ()
Dumps information about all registered modules, functions, classes and schemas into a string.
References automaton::core::interop::ethereum::string.
The documentation for this class was generated from the following files:
registry.h
registry.cc