Automaton Core: automaton::core::io Namespace Reference
automaton::core::io Namespace Reference
Classes
struct blob
struct ColorCoutSink
Functions
std::string bin2hex (const std::string &input)
std::string dec2hex (uint32_t n)
bool file_exists (const char *filename)
std::string get_date_string (std::chrono::system_clock::time_point t)
std::string get_file_contents (const char *filename)
std::string hex2bin (const std::string &input)
uint32_t hex2dec (const std::string &hex)
uint8_t hex2nibble (char c)
bool init_logger ()
std::string zero_padded (int num, int width)
Variables
const char * DEFAILT_LOG_OUTPUT_FILENAME = "automaton-core.log"
const char * DEFAULT_LOG_CONFIG_FILENAME = "log.cfg"
static const char *const hex_lut = "0123456789ABCDEF"
Function Documentation
bin2hex()
std::string automaton::core::io::bin2hex (const std::string & input)
Converts binary byte buffer to hex string representation.
References hex_lut, and automaton::core::interop::ethereum::string.
Referenced by automaton::core::script::engine::bind_io(), automaton::core::interop::ethereum::eth_contract::call(), check_and_sign(), automaton::core::interop::ethereum::check_and_sign(), automaton::core::interop::ethereum::decode_param(), automaton::core::state::state_impl::delete_node_tree(), automaton::core::state::state_persistent::delete_node_tree(), automaton::core::state::state_impl::erase(), automaton::core::state::state_persistent::erase(), automaton::tools::miner::gen_pub_key(), rpc_server_handler::handle(), main(), automaton::tools::miner::mine_key(), automaton::core::state::state_impl::print_subtrie(), automaton::core::state::state_persistent::print_subtrie(), automaton::core::node::luanode::lua_node::process_cmd(), automaton::core::interop::ethereum::eth_transaction::sign_tx(), and automaton::core::io::blob::tostring().
dec2hex()
std::string automaton::core::io::dec2hex (uint32_t n)
Returns string representing hex value of a number. Does not contain base prefix 0x. Length is always even.
Referenced by main(), automaton::core::interop::ethereum::rlp_encode(), and automaton::core::interop::ethereum::eth_transaction::sign_tx().
file_exists()
bool automaton::core::io::file_exists (const char * filename)
Checks whether the specified file exist.
Returns true if it does.
get_date_string()
std::string automaton::core::io::get_date_string (std::chrono::system_clock::time_point t)
Returns string representation of a date.
References automaton::core::interop::ethereum::string.
Referenced by automaton::core::node::node::log().
get_file_contents()
std::string automaton::core::io::get_file_contents (const char * filename)
Gets the file contents and returns them as a string.
Exception is thrown when error occurs.
References automaton::core::interop::ethereum::string.
Referenced by automaton::core::smartproto::smart_protocol::load(), and main().
hex2bin()
std::string automaton::core::io::hex2bin (const std::string & input)
Creates a binary byte buffer from hex string representation.
References hex2nibble(), and automaton::core::interop::ethereum::string.
Referenced by automaton::core::script::engine::bind_io(), automaton::core::interop::ethereum::encode_param(), main(), and automaton::core::interop::ethereum::eth_transaction::sign_tx().
hex2dec()
uint32_t automaton::core::io::hex2dec (const std::string & hex)
Returns a number from its hex representation.
Referenced by main(), automaton::core::interop::ethereum::rlp_encode(), and automaton::core::interop::ethereum::eth_transaction::sign_tx().
hex2nibble()
uint8_t automaton::core::io::hex2nibble (char c)
Referenced by hex2bin().
init_logger()
bool automaton::core::io::init_logger ()
References automaton::core::io::ColorCoutSink::ReceiveLogMessage().
Referenced by main().
zero_padded()
std::string automaton::core::io::zero_padded (int num, int width)
Referenced by automaton::core::node::node::log().
Variable Documentation
DEFAILT_LOG_OUTPUT_FILENAME
const char* automaton::core::io::DEFAILT_LOG_OUTPUT_FILENAME = "automaton-core.log"
DEFAULT_LOG_CONFIG_FILENAME
const char* automaton::core::io::DEFAULT_LOG_CONFIG_FILENAME = "log.cfg"
hex_lut
const char* const automaton::core::io::hex_lut = "0123456789ABCDEF" static
Referenced by bin2hex().