Automaton Core: automaton::core::network::acceptor::acceptor_handler Class Reference
automaton::core::network::acceptor::acceptor_handler Class Reference abstract
#include <acceptor.h>
Public Member Functions
virtual ~acceptor_handler ()
virtual void on_acceptor_error (acceptor_id a, const common::status &s)=0
virtual void on_connected (acceptor_id a, std::shared_ptr< connection > c, const std::string &address)=0
virtual bool on_requested (acceptor_id a, const std::string &address, connection_id *id)=0
Detailed Description
Handler class used to inform the client for events.
on_requested will be invoked when a peer wants to connect; it passes the address of the remote peer.
on_connected will be invoked if the connection was accepted by the user and new connection was made; it passes a shared pointer of the resulting connection
on_error will be invoked when an error happens while listening or accepting.
Constructor & Destructor Documentation
~acceptor_handler()
virtual automaton::core::network::acceptor::acceptor_handler::~acceptor_handler () inline virtual
Member Function Documentation
on_acceptor_error()
virtual void automaton::core::network::acceptor::acceptor_handler::on_acceptor_error (acceptor_id a, const common::status & s) pure virtual
Will be invoked when an error occurred while listening for or accepting connection to notify the user about the event.
Parameters
[in] a the id of the acceptor
[in] s status containing the error type and a description
See also
common::status
Referenced by automaton::core::network::tcp_acceptor::start_accepting().
on_connected()
virtual void automaton::core::network::acceptor::acceptor_handler::on_connected (acceptor_id a, std::shared_ptr< connection > c, const std::string & address) pure virtual
Will be called when a connection is accepted, passing the newly created connection.
Parameters
[in] a the id of the acceptor that accepted the connection
[in] c the newly created connection
[in] address the address of the accepted connection as it was when on_requested was invoked
Referenced by automaton::core::network::tcp_acceptor::start_accepting().
on_requested()
virtual bool automaton::core::network::acceptor::acceptor_handler::on_requested (acceptor_id a, const std::string & address, connection_id * id) pure virtual
Will be invoked when a peer sends a connection request. If this function returns true, new connection will be created and passed later with on_connected or on_acceptor_error will be called if an error occures.
Parameters
[in] a the id of the acceptor that caused the event
[in] address the address of the peer requesting the connection
[out] id the id to be assigned to the newly created connection if the function returns true. If it returns false, id is ignored
Returns
true if the user want to accept a connection from this address, false otherwise
Referenced by automaton::core::network::tcp_acceptor::start_accepting().
The documentation for this class was generated from the following file:
acceptor.h