Automaton Core: automaton::core::network::tcp_connection Class Reference
automaton::core::network::tcp_connection Class Reference
#include <tcp_implementation.h>
Public Member Functions
tcp_connection (connection_id id, const std::string &address_, const boost::asio::ip::tcp::socket &socket_, std::shared_ptr< connection_handler > handler_)
tcp_connection (connection_id id, const std::string &address_, std::shared_ptr< connection_handler > handler_)
~tcp_connection ()
void add_handler (std::shared_ptr< connection_handler > handler_)
void async_read (std::shared_ptr< char > buffer, uint32_t buffer_size, uint32_t num_bytes, uint32_t id)
void async_send (const std::string &msg, uint32_t id)
void connect ()
void disconnect ()
std::string get_address () const
connection::state get_state () const
bool init ()
Initialises the connection.
Public Member Functions inherited from automaton::core::network::connection
virtual ~connection ()
connection_id get_id ()
Additional Inherited Members
Public Types inherited from automaton::core::network::connection
typedef std::shared_ptr< connection >(* factory_function) (connection_id id, const std::string &address, std::shared_ptr< connection_handler > handler)
enum state { invalid_state = 0, connecting = 1, connected = 2, disconnected = 3 }
Static Public Member Functions inherited from automaton::core::network::connection
static std::shared_ptr< connection > create (const std::string &type, connection_id id, const std::string &address, std::shared_ptr< connection_handler > handler)
static void register_connection_type (const std::string &type, factory_function func)
Protected Member Functions inherited from automaton::core::network::connection
connection (connection_id id, std::shared_ptr< connection_handler > handler_)
Protected Attributes inherited from automaton::core::network::connection
std::shared_ptr< connection_handler > handler
connection_id id
Detailed Description
Class that represents a connection with a remote peer.
Constructor & Destructor Documentation
tcp_connection() [1/2]
automaton::core::network::tcp_connection::tcp_connection (connection_id id, const std::string & address_, std::shared_ptr< connection_handler > handler_)
Constructor that will be used when this class is registered.
See also
connection::create
Parameters
[in] address_ string representing the address of the connection - ip:port
References automaton::core::network::asio_io_service.
tcp_connection() [2/2]
automaton::core::network::tcp_connection::tcp_connection (connection_id id, const std::string & address_, const boost::asio::ip::tcp::socket & socket_, std::shared_ptr< connection_handler > handler_)
Constructor that should be used ONLY from the acceptor. It is used when there is a connection request and the user has accepted it.
See also
acceptor::acceptor_handler::on_requested
acceptor::acceptor_handler::on_connected
Parameters
[in] id identifier given by the user. It is used in connection_handler's functions to specify the connection invoked the function.
[in] address_ string representing the address of the connection - ip:port
[in] handler pointer to an connection_handler.
[in] socket_ the boost::asio::ip::tcp::socket on which the new connection was accepted.
~tcp_connection()
automaton::core::network::tcp_connection::~tcp_connection ()
Destructor.
Member Function Documentation
add_handler()
void automaton::core::network::tcp_connection::add_handler (std::shared_ptr< connection_handler > handler_)
This function is used to change the handler. It may be necessary when a connection is created from the acceptor and the default handler (the one passed to the acceptor) needs to be changed.
async_read()
void automaton::core::network::tcp_connection::async_read (std::shared_ptr< char > buffer, uint32_t buffer_size, uint32_t num_bytes, uint32_t id) virtual
See also
connection::async_read
Precondition
tcp_initialized == true meaning tcp_init() to be called
socket to be open. Socket opens on connection construction or when connect() is called and didn't fail. If disconnect() has been called, connect() should be called before this function.
If any of the preconditions is not met on_connection_error() will be called with status::internal, containing an error.
See also
common::status
If you call this function more than once, events form a queue, no read is cancelled. If an error occures during sending, on_connection_error() will be called with status, containing the error. If the error is boost::asio::error::eof (meaning the other peer has disconnected), disconnect() will be called too.
Implements automaton::core::network::connection.
References automaton::core::network::connection::handler, automaton::core::network::connection::id, automaton::core::interop::ethereum::string, and automaton::core::network::tcp_initialized.
async_send()
void automaton::core::network::tcp_connection::async_send (const std::string & msg, uint32_t id) virtual
See also
connection::async_send
Precondition
tcp_initialized == true meaning tcp_init() to be called
socket to be open. Socket opens on connection construction or when connect() is called and didn't fail. If disconnect() has been called, connect() should be called before this function.
msg.size() > 0
If any of the preconditions is not met on_message_sent() will be called with status, containing an error
See also
common::status
If an error occures during sending, on_message_sent() will be called with status, containing the error. If the error is broken pipe, disconnect() will be called too.
Implements automaton::core::network::connection.
References automaton::core::network::connection::handler, automaton::core::network::connection::id, automaton::core::network::connection::connection_handler::on_message_sent(), automaton::core::interop::ethereum::string, and automaton::core::network::tcp_initialized.
connect()
void automaton::core::network::tcp_connection::connect () virtual
Asynchronous connect. If an error occures, disconnect will be called and also handler's on_connection_error with status::unknown and a message containing the error. Status is changed to connecting. If a connection is successfully made, handler's on_connected will be called and the state is set to connected.
Implements automaton::core::network::connection.
References get_state(), automaton::core::network::connection::handler, automaton::core::network::connection::id, automaton::core::network::connection::connection_handler::on_connected(), automaton::core::network::connection::connection_handler::on_connection_error(), automaton::core::interop::ethereum::string, and automaton::core::network::tcp_initialized.
disconnect()
void automaton::core::network::tcp_connection::disconnect () virtual
This function can be called to disconnect peer. To reconnect, connect() should be called. Handler's on_disconnected() will be called on successful disconnect, on_connection_error(), otherwise.
Implements automaton::core::network::connection.
get_address()
std::string automaton::core::network::tcp_connection::get_address () const virtual
Returns
the connection address
Implements automaton::core::network::connection.
get_state()
connection::state automaton::core::network::tcp_connection::get_state () const virtual
Returns
the connection state
Implements automaton::core::network::connection.
Referenced by connect().
init()
bool automaton::core::network::tcp_connection::init () virtual
Initialises the connection.
Precondition
tcp_init() to has been called before, error will happen, otherwise
Parses the address and tries to create an endpoint. If it succeeds, connection state will be set to disconnected, error will be logged, otherwise.
Returns
true if the initialisation is successful, false if an error occures. If there was an error while initialisation, it will be logged.
Implements automaton::core::network::connection.
References automaton::core::network::asio_io_service, automaton::core::network::parse_address(), automaton::core::interop::ethereum::string, and automaton::core::network::tcp_initialized.
The documentation for this class was generated from the following files:
tcp_implementation.h
tcp_implementation.cc