Automaton Core: automaton::core::cli::cli Class Reference
automaton::core::cli::cli Class Reference
#include <cli.h>
Public Member Functions
cli ()
std::vector< std::string > get_hints ()
void hints_add (const char *cmd)
void hints_clear ()
void history_add (const char *cmd)
char const * input (const char *prompt)
void print (const char *msg)
Constructor & Destructor Documentation
cli()
automaton::core::cli::cli::cli ()
References automaton::core::cli::hook_color(), automaton::core::cli::hook_completion(), and automaton::core::cli::hook_hint().
Member Function Documentation
get_hints()
std::vector< std::string > automaton::core::cli::cli::get_hints ()
hints_add()
void automaton::core::cli::cli::hints_add (const char * cmd)
Referenced by main().
hints_clear()
void automaton::core::cli::cli::hints_clear ()
Referenced by main().
history_add()
void automaton::core::cli::cli::history_add (const char * cmd)
Referenced by main().
input()
char const * automaton::core::cli::cli::input (const char * prompt)
Referenced by main().
print()
void automaton::core::cli::cli::print (const char * msg)
Referenced by main().
The documentation for this class was generated from the following files:
cli.h
cli.cc