Automaton Core: core.cc File Reference
core.cc File Reference
#include <curl/curl.h>
#include <cryptopp/base64.h>
#include <cryptopp/filters.h>
#include <future>
#include <fstream>
#include <iostream>
#include <regex>
#include <string>
#include <json.hpp>
#include "automaton/core/cli/cli.h"
#include "automaton/core/common/versions.h"
#include "automaton/core/data/factory.h"
#include "automaton/core/data/protobuf/protobuf_factory.h"
#include "automaton/core/data/protobuf/protobuf_schema.h"
#include "automaton/core/network/http_server.h"
#include "automaton/core/network/simulated_connection.h"
#include "automaton/core/network/tcp_implementation.h"
#include "automaton/core/node/lua_node/lua_node.h"
#include "automaton/core/node/node_updater.h"
#include "automaton/core/node/node.h"
#include "automaton/core/script/engine.h"
#include "automaton/core/smartproto/smart_protocol.h"
#include "automaton/core/testnet/testnet.h"
#include "automaton/core/io/io.h"
Classes
class rpc_server_handler
Typedefs
using json = nlohmann::json
Functions
int main (int argc, char *argv[])
void string_replace (string *str, const string &oldStr, const string &newStr)
Typedef Documentation
json
using json = nlohmann::json
Function Documentation
main()
int main (int argc, char * argv[])
References automaton::core::node::peer_info::address, automaton::core::script::engine::bind_core(), automaton::core::node::node::get_acceptor(), automaton::core::network::acceptor::get_address(), automaton::core::io::get_file_contents(), automaton::core::node::node::get_peer_info(), automaton::core::network::simulation::get_simulator(), automaton::core::cli::cli::hints_add(), automaton::core::cli::cli::hints_clear(), automaton::core::cli::cli::history_add(), automaton::core::script::engine::import_schema(), automaton::core::io::init_logger(), automaton::core::cli::cli::input(), automaton::core::node::node::list_connected_peers(), automaton::core::node::node::list_known_peers(), automaton::core::testnet::testnet::list_nodes(), nodes, automaton::core::cli::cli::print(), automaton::core::network::http_server::run(), automaton::core::node::luanode::lua_node::script(), automaton::core::network::simulation::simulation_start(), automaton::core::network::simulation::simulation_stop(), automaton::core::network::http_server::stop(), automaton::core::interop::ethereum::string, string_replace(), automaton::core::network::tcp_init(), and automaton::core::network::tcp_release().
string_replace()
void string_replace (string * str, const string & oldStr, const string & newStr)
Referenced by main().