Automaton Core: automaton::core::common::versions Class Reference
automaton::core::common::versions Class Reference
#include <versions.h>
Static Public Member Functions
static unsigned automaton_core_major ()
static unsigned automaton_core_minor ()
static unsigned automaton_core_revision ()
static std::string automaton_core_version_string ()
Member Function Documentation
automaton_core_major()
static unsigned automaton::core::common::versions::automaton_core_major () inline static
References AUTOMATON_CORE_VERSION_MAJOR.
Referenced by automaton_core_version_string().
automaton_core_minor()
static unsigned automaton::core::common::versions::automaton_core_minor () inline static
References AUTOMATON_CORE_VERSION_MINOR.
Referenced by automaton_core_version_string().
automaton_core_revision()
static unsigned automaton::core::common::versions::automaton_core_revision () inline static
References AUTOMATON_CORE_VERSION_REVISION.
Referenced by automaton_core_version_string().
automaton_core_version_string()
static std::string automaton::core::common::versions::automaton_core_version_string () inline static
References automaton_core_major(), automaton_core_minor(), and automaton_core_revision().
The documentation for this class was generated from the following file:
versions.h