Automaton Core: automaton::core::state::state_impl Class Reference
automaton::core::state::state_impl Class Reference
#include <state_impl.h>
Public Member Functions
state_impl (crypto::hash_transformation *hasher)
void commit_changes ()
void delete_node_tree (const std::string &path)
void discard_changes ()
void erase (const std::string &path)
std::string get (const std::string &key)
std::vector< std::string > get_node_children (const std::string &path)
std::string get_node_hash (const std::string &path)
uint32_t hash_size ()
void print_subtrie (std::string path, std::string formated_path)
void set (const std::string &key, const std::string &value)
uint32_t size ()
Public Member Functions inherited from automaton::core::state::state
virtual ~state ()
Constructor & Destructor Documentation
state_impl()
automaton::core::state::state_impl::state_impl (crypto::hash_transformation * hasher) explicit
Member Function Documentation
commit_changes()
void automaton::core::state::state_impl::commit_changes () virtual
Implements automaton::core::state::state.
delete_node_tree()
void automaton::core::state::state_impl::delete_node_tree (const std::string & path) virtual
Implements automaton::core::state::state.
References automaton::core::io::bin2hex().
discard_changes()
void automaton::core::state::state_impl::discard_changes () virtual
Implements automaton::core::state::state.
erase()
void automaton::core::state::state_impl::erase (const std::string & path) virtual
Implements automaton::core::state::state.
References automaton::core::io::bin2hex().
Referenced by set().
get()
std::string automaton::core::state::state_impl::get (const std::string & key) virtual
Implements automaton::core::state::state.
Referenced by print_subtrie().
get_node_children()
std::vector< std::string > automaton::core::state::state_impl::get_node_children (const std::string & path) virtual
Implements automaton::core::state::state.
References automaton::core::interop::ethereum::string.
Referenced by print_subtrie().
get_node_hash()
std::string automaton::core::state::state_impl::get_node_hash (const std::string & path) virtual
Implements automaton::core::state::state.
Referenced by print_subtrie().
hash_size()
uint32_t automaton::core::state::state_impl::hash_size () virtual
Implements automaton::core::state::state.
References automaton::core::crypto::hash_transformation::digest_size().
print_subtrie()
void automaton::core::state::state_impl::print_subtrie (std::string path, std::string formated_path)
References automaton::core::io::bin2hex(), get(), get_node_children(), and get_node_hash().
set()
void automaton::core::state::state_impl::set (const std::string & key, const std::string & value) virtual
Implements automaton::core::state::state.
References erase(), and automaton::core::interop::ethereum::string.
size()
uint32_t automaton::core::state::state_impl::size ()
The documentation for this class was generated from the following files:
state_impl.h
state_impl.cc