Automaton Core: automaton::core::network::simulation Class Reference
automaton::core::network::simulation Class Reference
#include <simulated_connection.h>
Public Member Functions
~simulation ()
void add_acceptor (uint32_t address, std::shared_ptr< acceptor > acceptor_)
void add_connection (std::shared_ptr< connection > connection_)
void add_handlers_task (std::function< void()> task)
void add_task (uint64_t tm, std::function< void()> task)
std::shared_ptr< acceptor > get_acceptor (uint32_t address)
std::shared_ptr< connection > get_connection (uint32_t connection_id)
uint64_t get_time ()
void handle_accept (uint32_t dest)
void handle_ack (uint32_t dest, const automaton::core::common::status &s)
void handle_disconnect (uint32_t dest)
void handle_message (uint32_t source, uint32_t destination, const std::string &message)
void handle_refuse (uint32_t dest)
void handle_request (uint32_t src, uint32_t dest)
bool is_queue_empty ()
uint32_t process (uint64_t time)
void process_handlers ()
void remove_acceptor (uint32_t address)
void remove_connection (uint32_t connection_id)
void simulation_start (uint64_t millisec_step)
void simulation_stop ()
Static Public Member Functions
static std::shared_ptr< simulation > get_simulator ()
Detailed Description
Singleton class running the simulation. Stores created acceptors, connections and simulation time. Handle event queue.
Constructor & Destructor Documentation
~simulation()
automaton::core::network::simulation::~simulation ()
Member Function Documentation
add_acceptor()
void automaton::core::network::simulation::add_acceptor (uint32_t address, std::shared_ptr< acceptor > acceptor_)
add_connection()
void automaton::core::network::simulation::add_connection (std::shared_ptr< connection > connection_)
Referenced by handle_request().
add_handlers_task()
void automaton::core::network::simulation::add_handlers_task (std::function< void()> task)
Referenced by handle_accept(), handle_ack(), handle_disconnect(), handle_refuse(), and handle_request().
add_task()
void automaton::core::network::simulation::add_task (uint64_t tm, std::function< void()> task)
Referenced by handle_accept(), handle_ack(), handle_disconnect(), handle_message(), handle_refuse(), and handle_request().
get_acceptor()
std::shared_ptr< acceptor > automaton::core::network::simulation::get_acceptor (uint32_t address)
Referenced by handle_request().
get_connection()
std::shared_ptr< connection > automaton::core::network::simulation::get_connection (uint32_t connection_id)
Referenced by handle_accept(), handle_ack(), handle_disconnect(), handle_message(), handle_refuse(), and handle_request().
get_simulator()
std::shared_ptr< simulation > automaton::core::network::simulation::get_simulator () static
Returns pointer to the simulation instance;
Referenced by automaton::core::network::simulated_connection::async_read(), automaton::core::network::simulated_connection::async_send(), automaton::core::network::simulated_connection::cancel_operations(), automaton::core::network::simulated_connection::connect(), automaton::core::network::simulated_connection::disconnect(), handle_message(), automaton::core::network::simulated_connection::handle_read(), handle_request(), automaton::core::network::simulated_connection::handle_send(), automaton::core::network::simulated_acceptor::init(), and main().
get_time()
uint64_t automaton::core::network::simulation::get_time ()
Returns current simulation time
Referenced by handle_accept(), handle_ack(), handle_disconnect(), handle_message(), handle_refuse(), handle_request(), and process().
handle_accept()
void automaton::core::network::simulation::handle_accept (uint32_t dest)
References add_handlers_task(), add_task(), get_connection(), and get_time().
Referenced by handle_request().
handle_ack()
void automaton::core::network::simulation::handle_ack (uint32_t dest, const automaton::core::common::status & s)
References add_handlers_task(), add_task(), get_connection(), and get_time().
Referenced by handle_message().
handle_disconnect()
void automaton::core::network::simulation::handle_disconnect (uint32_t dest)
This event is created when the other endpoint has called disconnect(). Sets connection state to disconnected.
References add_handlers_task(), add_task(), get_connection(), get_time(), and remove_connection().
Referenced by automaton::core::network::simulated_connection::disconnect().
handle_message()
void automaton::core::network::simulation::handle_message (uint32_t source, uint32_t destination, const std::string & message)
References add_task(), get_connection(), get_simulator(), get_time(), handle_ack(), automaton::core::network::simulated_connection::handle_read(), and automaton::core::network::simulated_connection::handle_send().
Referenced by automaton::core::network::simulated_connection::handle_send().
handle_refuse()
void automaton::core::network::simulation::handle_refuse (uint32_t dest)
References add_handlers_task(), add_task(), get_connection(), and get_time().
Referenced by handle_request().
handle_request()
void automaton::core::network::simulation::handle_request (uint32_t src, uint32_t dest)
This event is created when the other endpoint has called connect(). On_requested is called and if it returns true, new event with type accept is created, new connection is created from this endpoint to the other, the new connection's state is set to connected and on_connect in acceptor's handler is called. If the connections is refused, new event type refuse is created.
References add_connection(), add_handlers_task(), add_task(), get_acceptor(), get_connection(), get_simulator(), get_time(), handle_accept(), handle_refuse(), automaton::core::network::connection_params::max_lag, automaton::core::network::connection_params::min_lag, and automaton::core::interop::ethereum::string.
Referenced by automaton::core::network::simulated_connection::connect().
is_queue_empty()
bool automaton::core::network::simulation::is_queue_empty ()
Checks if the event/task queue is empty.
process()
uint32_t automaton::core::network::simulation::process (uint64_t time)
Process all events from simulation_time to the given time.
References get_time().
Referenced by simulation_start().
process_handlers()
void automaton::core::network::simulation::process_handlers ()
Referenced by simulation_start().
remove_acceptor()
void automaton::core::network::simulation::remove_acceptor (uint32_t address)
remove_connection()
void automaton::core::network::simulation::remove_connection (uint32_t connection_id)
Referenced by handle_disconnect().
simulation_start()
void automaton::core::network::simulation::simulation_start (uint64_t millisec_step)
If called, process will be invoked every millisec_step milliseconds + the process time. New thread is started. Simulation_stop should be called so the thread can be stopped and joined.
References process(), and process_handlers().
Referenced by main().
simulation_stop()
void automaton::core::network::simulation::simulation_stop ()
Stops the simulation and joins the process thread. Needs to be called at the end of the program.
Referenced by main().
The documentation for this class was generated from the following files:
simulated_connection.h
simulated_connection.cc