Automaton Core: automaton::core::node::luanode::lua_node Class Reference
automaton::core::node::luanode::lua_node Class Reference
#include <lua_node.h>
Public Member Functions
lua_node (const std::string &id, const std::string &proto_id)
~lua_node ()
std::unique_ptr< data::msg > create_msg_by_id (uint32_t id)
uint32_t find_message_id (const std::string &name)
void init ()
std::string process_cmd (const std::string &cmd, const std::string &params)
void script (const std::string &command, std::promise< std::string > *result)
Public Member Functions inherited from automaton::core::node::node
~node ()
peer_id add_peer (const std::string &address)
bool connect (peer_id id)
bool disconnect (peer_id id)
void dump_logs (const std::string &html_file)
std::shared_ptr< network::acceptor > get_acceptor ()
std::string get_id () const
peer_info get_peer_info (peer_id id)
std::string get_protocol_id () const
uint64_t get_time_to_update ()
std::set< peer_id > list_connected_peers ()
std::vector< peer_id > list_known_peers ()
void log (const std::string &logger, const std::string &msg)
void process_update (uint64_t current_time)
void remove_peer (peer_id id)
void send_blob (peer_id id, const std::string &blob, uint32_t msg_id)
void send_message (peer_id id, const data::msg &msg, uint32_t msg_id)
bool set_acceptor (const std::string &address)
bool set_peer_info (peer_id id, const peer_info &info)
Public Member Functions inherited from automaton::core::network::connection::connection_handler
virtual ~connection_handler ()
Public Member Functions inherited from automaton::core::network::acceptor::acceptor_handler
virtual ~acceptor_handler ()
Additional Inherited Members
Public Types inherited from automaton::core::node::node
typedef std::shared_ptr< node >(* factory_function) (const std::string &id, const std::string &proto_id)
Static Public Member Functions inherited from automaton::core::node::node
static std::shared_ptr< node > create (const std::string &type, const std::string &id, const std::string &proto_id)
static std::shared_ptr< node > get_node (const std::string &node_id)
static bool launch_node (const std::string &node_type, const std::string &node_id, const std::string &protocol_id, const std::string &address)
static std::vector< std::string > list_nodes ()
static void register_node_type (const std::string &type, factory_function func)
static void remove_node (const std::string &node_id)
Protected Member Functions inherited from automaton::core::node::node
node (const std::string &id, const std::string &proto_id)
void add_task (std::function< std::string()> task)
std::unique_ptr< data::msg > create_msg_by_id (uint32_t id, std::shared_ptr< data::factory > factory)
uint32_t find_message_id (const std::string &name, std::shared_ptr< data::factory > factory)
std::unique_ptr< data::msg > get_wire_msg (const std::string &blob)
Protected Attributes inherited from automaton::core::node::node
std::string nodeid
std::string protoid
std::mutex script_mutex
Constructor & Destructor Documentation
lua_node()
automaton::core::node::luanode::lua_node::lua_node (const std::string & id, const std::string & proto_id)
~lua_node()
automaton::core::node::luanode::lua_node::~lua_node ()
Member Function Documentation
create_msg_by_id()
std::unique_ptr<data::msg> automaton::core::node::luanode::lua_node::create_msg_by_id (uint32_t id) inline
References automaton::core::node::node::create_msg_by_id(), and automaton::core::script::engine::get_factory().
find_message_id()
uint32_t automaton::core::node::luanode::lua_node::find_message_id (const std::string & name) inline
References automaton::core::node::node::find_message_id(), and automaton::core::script::engine::get_factory().
init()
void automaton::core::node::luanode::lua_node::init () virtual
Implements automaton::core::node::node.
References automaton::core::smartproto::smart_protocol::get_commands(), automaton::core::smartproto::smart_protocol::get_factory(), automaton::core::smartproto::smart_protocol::get_files(), automaton::core::smartproto::smart_protocol::get_protocol(), automaton::core::smartproto::smart_protocol::get_schemas(), automaton::core::smartproto::smart_protocol::get_wire_msgs(), automaton::core::node::node::protoid, and automaton::core::script::engine::set_factory().
process_cmd()
std::string automaton::core::node::luanode::lua_node::process_cmd (const std::string & cmd, const std::string & params) virtual
Reimplemented from automaton::core::node::node.
References automaton::core::io::bin2hex(), automaton::core::node::node::script_mutex, and automaton::core::interop::ethereum::string.
script()
void automaton::core::node::luanode::lua_node::script (const std::string & command, std::promise< std::string > * result) virtual
Reimplemented from automaton::core::node::node.
References automaton::core::node::node::add_task().
Referenced by main().
The documentation for this class was generated from the following files:
lua_node.h
lua_node.cc